from __future__ import annotations

from datetime import UTC, datetime
from typing import Any


class BaseReportTemplate:
    def __init__(self, title: str = "Report", css: str = ""):
        self._title = title
        self._css = (
            css
            or """
body { font-family: 'Segoe UI', Tahoma, sans-serif; margin: 40px; color: #333; }
h1 { color: #1a5276; border-bottom: 2px solid #2980b9; padding-bottom: 10px; }
h2 { color: #2c3e50; margin-top: 30px; }
table { border-collapse: collapse; width: 100%; margin: 15px 0; }
th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
th { background-color: #2980b9; color: white; }
tr:nth-child(even) { background-color: #f8f9fa; }
tr:hover { background-color: #eaf2f8; }
.section { margin: 20px 0; padding: 15px; background: #f8f9fa; border-radius: 5px; }
.footer { margin-top: 40px; font-size: 12px; color: #7f8c8d; text-align: center; }
.metric { display: inline-block; margin: 10px; padding: 15px; background: #fff; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
.metric-value { font-size: 24px; font-weight: bold; color: #2980b9; }
.metric-label { font-size: 12px; color: #7f8c8d; }
"""
        )

    def render(self, data: dict[str, Any]) -> str:
        title = data.get("title", self._title)
        report_type = data.get("report_type", "report")
        generated_at = data.get("generated_at", datetime.now(UTC).isoformat())
        body_parts: list[str] = []
        body_parts.append(f"<h1>{title}</h1>")
        body_parts.append(f'<p class="meta">Type: {report_type} | Generated: {generated_at}</p>')
        for key, value in data.items():
            if key in ("title", "report_type", "generated_at"):
                continue
            if isinstance(value, list) and value:
                body_parts.append(self._render_table(key, value))
            elif isinstance(value, dict) and value:
                body_parts.append(self._render_dict(key, value))
            else:
                body_parts.append(f'<div class="section"><strong>{key}:</strong> {value}</div>')
        body = "\n".join(body_parts)
        return f"""<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head><meta charset="utf-8"><title>{title}</title>
<style>{self._css}</style></head>
<body>{body}
<div class="footer">Generated by Iran Market Platform at {generated_at}</div>
</body></html>"""

    def _render_table(self, title: str, rows: list[Any]) -> str:
        if not rows:
            return f"<h2>{title}</h2><p>No data</p>"
        if isinstance(rows[0], dict):
            headers = list(rows[0].keys())
            thead = "".join(f"<th>{h}</th>" for h in headers)
            tbody = ""
            for row in rows:
                tbody += "<tr>" + "".join(f"<td>{self._format(row.get(h, ''))}</td>" for h in headers) + "</tr>"
            return f"<h2>{title}</h2><table><thead><tr>{thead}</tr></thead><tbody>{tbody}</tbody></table>"
        items = "".join(f"<li>{self._format(r)}</li>" for r in rows)
        return f"<h2>{title}</h2><ul>{items}</ul>"

    def _render_dict(self, title: str, d: dict[str, Any]) -> str:
        rows = "".join(f"<tr><td>{k}</td><td>{self._format(v)}</td></tr>" for k, v in d.items())
        return f"<h2>{title}</h2><table><tbody>{rows}</tbody></table>"

    def _format(self, value: Any) -> str:
        if isinstance(value, float):
            return f"{value:,.2f}"
        if isinstance(value, (int,)):
            return f"{value:,}"
        if value is None:
            return "-"
        return str(value)
