"""🏦 The pre-buy question bank: 11 stages, 115 questions, 15 ★ stoppers, 5 golden.

Content only — no judgement here. The gate lives in :mod:`core.question_bank.engine`.

Transcribed from «بانک سؤالات پیش از خرید سهم — نسخه پرسشی چارچوب کامل».
Numbering is contiguous (``PB-001`` … ``PB-115``) so a stored answer keeps pointing at
the same question even if a stage is later reworded; ``tests`` assert the counts and the
uniqueness, because a silently duplicated code would corrupt every saved sheet.
"""

from __future__ import annotations

from core.question_bank.schema import (
    UNKNOWN,
    Evidence,
    Input,
    Option,
    Question,
    Stage,
)

_YES_NO = (
    Option("yes", "بله"),
    Option("no", "خیر"),
    Option(UNKNOWN, "نمی‌دانم"),
)

_STAGES: tuple[Stage, ...] = (
    Stage(0, "self", "سؤالات از خودم", "پیش از نگاه به هر نماد",
          "بدون پاسخ به این مرحله، سراغ هیچ نمادی نرو."),
    Stage(1, "screen", "غربال حذفی", "حذف سریع نمادهای نامناسب",
          "پاسخ نامناسب = کنار گذاشتن؛ ★های این مرحله ردکننده‌اند."),
    Stage(2, "business", "کسب‌وکار و صنعت", "فهم درآمد و جایگاه رقابتی", ""),
    Stage(3, "financial", "کیفیت مالی", "صورت‌های مالی و جریان نقد", ""),
    Stage(4, "iran", "سؤالات خاص ایران", "دستوری بودن نرخ، ارز، تحریم و سهامدار عمده",
          "اینجا بیشترین تحلیل‌های اشتباه رخ می‌دهد."),
    Stage(5, "valuation", "ارزش‌گذاری", "محدوده ارزش و حاشیه اطمینان",
          "محدوده بده، نه یک عدد دقیق."),
    Stage(6, "catalyst", "محرک و زمان‌بندی", "چرا الان؟", ""),
    Stage(7, "technical", "تکنیکال و اجرای سفارش", "نقطه ورود، حد ابطال و هزینه اجرا", ""),
    Stage(8, "sizing", "اندازه موقعیت و ریسک سبد", "حجم خرید از فرمول ریسک", ""),
    Stage(9, "exit", "طرح فروش", "خروج، هدف و شرط ابطال",
          "باید پیش از خرید نوشته شود."),
    Stage(10, "mirror", "خودکنترلی نهایی", "آینه — تشخیص سوگیری‌ها", ""),
)


def _e(key: str, label: str, source: str, unit: str = "") -> Evidence:
    return Evidence(key=key, label=label, source=source, unit=unit)


# Evidence handles. The resolver in services/pre_buy_evidence.py implements exactly this
# set; a test fails the build if the two drift apart.
_E = {
    "detail.name": _e("detail.name", "نام شرکت", "GET /brsapi/symbol-details/{symbol}"),
    "detail.state": _e("detail.state", "وضعیت معاملات", "GET /brsapi/symbol-details/{symbol}"),
    "detail.board": _e("detail.board", "تابلو/بازار", "GET /brsapi/symbol-details/{symbol}"),
    "detail.sector": _e("detail.sector", "گروه/زیرگروه", "GET /brsapi/symbol-details/{symbol}"),
    "detail.price_last": _e("detail.price_last", "قیمت آخرین", "GET /brsapi/symbol-details/{symbol}", "ریال"),
    "detail.price_yesterday": _e("detail.price_yesterday", "قیمت دیروز", "GET /brsapi/symbol-details/{symbol}", "ریال"),
    "detail.price_min_year": _e("detail.price_min_year", "کمترین ۵۲ هفته", "GET /brsapi/symbol-details/{symbol}", "ریال"),
    "detail.price_max_year": _e("detail.price_max_year", "بیشترین ۵۲ هفته", "GET /brsapi/symbol-details/{symbol}", "ریال"),
    "detail.tmin": _e("detail.tmin", "کف دامنه مجاز", "GET /brsapi/symbol-details/{symbol}", "ریال"),
    "detail.tmax": _e("detail.tmax", "سقف دامنه مجاز", "GET /brsapi/symbol-details/{symbol}", "ریال"),
    "detail.base_volume": _e("detail.base_volume", "حجم مبنا", "GET /brsapi/symbol-details/{symbol}", "سهم"),
    "detail.trade_value": _e("detail.trade_value", "ارزش معاملات امروز", "GET /brsapi/symbol-details/{symbol}", "ریال"),
    "detail.avg_volume_month": _e("detail.avg_volume_month", "میانگین حجم ماه", "GET /brsapi/symbol-details/{symbol}", "سهم"),
    "detail.shares_count": _e("detail.shares_count", "تعداد سهام", "GET /brsapi/symbol-details/{symbol}", "سهم"),
    "detail.free_float": _e("detail.free_float", "درصد سهام شناور", "GET /brsapi/symbol-details/{symbol}", "٪"),
    "detail.eps": _e("detail.eps", "EPS", "GET /brsapi/symbol-details/{symbol}", "ریال"),
    "detail.pe": _e("detail.pe", "P/E", "GET /brsapi/symbol-details/{symbol}", "برابر"),
    "detail.group_pe": _e("detail.group_pe", "P/E گروه", "GET /brsapi/symbol-details/{symbol}", "برابر"),
    "detail.ps": _e("detail.ps", "P/S", "GET /brsapi/symbol-details/{symbol}", "برابر"),
    "detail.market_cap": _e("detail.market_cap", "ارزش بازار", "GET /brsapi/symbol-details/{symbol}", "ریال"),
    "codal.last_report": _e("codal.last_report", "تاریخ آخرین گزارش", "GET /codal/{symbol}"),
    "codal.report_count": _e("codal.report_count", "تعداد گزارش ۱۲ ماه", "GET /codal/{symbol}"),
    "codal.audit_status": _e("codal.audit_status", "اظهارنظر حسابرس", "GET /brsapi/codal-announcements"),
    "fin.revenue_growth": _e("fin.revenue_growth", "رشد درآمد", "GET /brsapi/codal/{symbol}"),
    "fin.net_profit_growth": _e("fin.net_profit_growth", "رشد سود خالص", "GET /brsapi/codal/{symbol}"),
    "fin.gross_margin": _e("fin.gross_margin", "حاشیه ناخالص", "GET /brsapi/codal/{symbol}", "٪"),
    "fin.net_margin": _e("fin.net_margin", "حاشیه خالص", "GET /brsapi/codal/{symbol}", "٪"),
    "fin.roe": _e("fin.roe", "ROE", "GET /brsapi/codal/{symbol}", "٪"),
    "fin.current_ratio": _e("fin.current_ratio", "نسبت جاری", "GET /brsapi/codal/{symbol}"),
    "fin.debt_to_equity": _e("fin.debt_to_equity", "بدهی به حقوق صاحبان", "GET /brsapi/codal/{symbol}"),
    "fin.asset_turnover": _e("fin.asset_turnover", "گردش دارایی", "GET /brsapi/codal/{symbol}"),
    "fin.earnings_quality": _e("fin.earnings_quality", "کیفیت سود", "GET /brsapi/codal/{symbol}"),
    "fin.forensic_risk": _e("fin.forensic_risk", "ریسک فورتزیک", "GET /brsapi/codal/{symbol}"),
    "holders.top_name": _e("holders.top_name", "بزرگ‌ترین سهامدار", "GET /stocks/v2/{symbol}/dossier"),
    "holders.top_pct": _e("holders.top_pct", "سهم بزرگ‌ترین سهامدار", "GET /stocks/v2/{symbol}/dossier", "٪"),
    "holders.institutional_pct": _e("holders.institutional_pct", "سهم حقوقی‌ها", "GET /codal/{symbol}/holders", "٪"),
    "queue.status": _e("queue.status", "وضعیت صف", "GET /queue-analysis/{symbol}"),
    "queue.days": _e("queue.days", "روزهای ماندن در صف", "GET /queue-analysis/{symbol}", "روز"),
    "queue.distance": _e("queue.distance", "فاصله تا سقف/کف دامنه", "GET /queue-analysis/{symbol}", "٪"),
    "flow.real_net": _e("flow.real_net", "خالص خرید حقیقی امروز", "GET /brsapi/symbol-details/{symbol}", "ریال"),
    "div.last_date": _e("div.last_date", "آخرین تقسیم سود", "GET /codal/{symbol}/dividends"),
    "signal.composite": _e("signal.composite", "امتیازcomposite سیستم", "GET /stocks/v2/{symbol}/signal"),
}


def _q(
    code: str,
    stage: int,
    text: str,
    kind: str,
    *,
    stopper: bool = False,
    hint: str = "",
    options: tuple[Option, ...] = (),
    veto_values: tuple[str, ...] = (),
    inputs: tuple[Input, ...] = (),
    unit: str = "",
    note_required: bool = False,
    evidence: tuple[str, ...] = (),
    golden: bool = False,
) -> Question:
    return Question(
        code=code,
        stage=stage,
        text=text,
        kind=kind,  # type: ignore[arg-type]
        stopper=stopper,
        hint=hint,
        options=options,
        veto_values=veto_values,
        inputs=inputs,
        unit=unit,
        note_required=note_required,
        evidence=tuple(_E[k] for k in evidence),
        golden=golden,
    )


_I = Input

_QUESTIONS: tuple[Question, ...] = (
    # ══════════════ مرحله ۰ — سؤالات از خودم (۱۱) ══════════════
    _q("PB-001", 0, "با چه هدفی می‌خرم: رشد سرمایه، سود نقدی، یا سود معاملاتی؟", "choice",
       options=(Option("growth", "رشد سرمایه"), Option("income", "سود نقدی (DPS)"),
                Option("trade", "سود معاملاتی"), Option(UNKNOWN, "نمی‌دانم", veto=True))),
    _q("PB-002", 0, "افق نگهداری دقیقاً چند ماه/سال است؟", "number",
       inputs=(_I("horizon_months", "افق (ماه)", "ماه", role="horizon_months", min=0, max=600),)),
    _q("PB-003", 0, "این پول تا پایان افق به هیچ خرج ضروری‌ای نیاز ندارد؟", "yes_no_unknown",
       stopper=True, options=_YES_NO, veto_values=("no",),
       hint="پولِ لازمِ فردا، سرمایهٔ قابل‌ریسک نیست."),
    _q("PB-004", 0, "حداکثر افت قابل‌تحمل کل سبد من چند درصد و چند تومان است؟", "number",
       inputs=(_I("drawdown_pct", "حداکثر افت سبد", "٪", role="max_drawdown_pct", min=0, max=100),
               _I("drawdown_toman", "حداکثر افت سبد", "تومان", role="max_drawdown_toman", min=0))),
    _q("PB-005", 0, "حداکثر زیان قابل‌قبول این یک معامله چقدر است؟", "number",
       inputs=(_I("max_loss_toman", "زیان مجاز این معامله", "تومان", role="max_loss_toman", min=0),),
       note_required=True, hint="عددِ مطلق؛ مبنای کل فرمول اندازهٔ موقعیت است."),
    _q("PB-006", 0, "سقف وزن هر سهم و هر صنعت در سبد من چقدر است؟", "number",
       inputs=(_I("stock_cap_pct", "سقف وزن سهم", "٪", role="weight_cap_pct", min=0, max=100),
               _I("sector_cap_pct", "سقف وزن صنعت", "٪", role="sector_cap_pct", min=0, max=100),)),
    _q("PB-007", 0, "اگر این روزها چند روز پشت‌سرهم سبد افت کند، از نظر روانی چه می‌کنم؟", "choice",
       options=(Option("plan", "دقیقاً طبق برنامهٔ نوشته‌شده"), Option("hold", "صبر می‌کنم"),
                Option("panic_sell", "می‌فروشم و از قبل تعیین نکرده‌ام", veto=True),
                Option(UNKNOWN, "نمی‌دانم", veto=True))),
    _q("PB-008", 0, "چند ساعت در هفته واقعاً می‌توانم برای پایش بگذارم؟", "number",
       inputs=(_I("hours_per_week", "ساعت در هفته", "ساعت", role="hours_per_week", min=0, max=168),),
       hint="اقلی از ۱ ساعت، افق کوتاه‌مدت و پرتفوی غیرفعال را رد می‌کند."),
    _q("PB-009", 0, "قواعد ورود و خروجم را از قبل نوشته‌ام یا در لحظه تصمیم می‌گیرم؟", "yes_no_unknown",
       options=_YES_NO, hint="«نوشته‌ام» یعنی یک سند، نه یک نیت."),
    _q("PB-010", 0, "بازده موردانتظارم با چه ریسکی باید به دست بیاید و می‌پذیرم؟", "text",
       note_required=True),
    _q("PB-011", 0, "معیار مقایسه‌ام چیست: شاخص کل، سپرده، طلا، دلار؟", "choice",
       options=(Option("index", "شاخص کل"), Option("deposit", "سپرده/اوراق"),
                Option("gold", "طلا/سکه"), Option("dollar", "دلار"),
                Option(UNKNOWN, "ندارم", veto=True))),

    # ══════════════ مرحله ۱ — غربال حذفی (۹) ══════════════
    _q("PB-012", 1, "آیا می‌توانم در ۳–۵ جمله توضیح دهم این شرکت چطور پول درمی‌آورد؟",
       "yes_no_unknown", stopper=True, options=_YES_NO, veto_values=("no",),
       evidence=("detail.name", "detail.sector")),
    _q("PB-013", 1, "آیا بدون اثر زیاد بر قیمت می‌توانم از موقعیتم خارج شوم؟ (میانگین ارزش معاملات روزانه چندماهه؟)",
       "yes_no_unknown", stopper=True, options=_YES_NO, veto_values=("no",),
       evidence=("detail.trade_value", "detail.avg_volume_month", "detail.base_volume", "detail.free_float")),
    _q("PB-014", 1, "گزارش‌های کدال منظم، کامل و به‌موقع است؟",
       "yes_no_unknown", stopper=True, options=_YES_NO, veto_values=("no",),
       evidence=("codal.last_report", "codal.report_count")),
    _q("PB-015", 1, "اظهارنظر حسابرس چیست؟ بند شرط یا تأکید بر تداوم فعالیت هست؟",
       "choice", stopper=True,
       options=(Option("clean", "مقید نیست"), Option("emphasis", "بدون بند، با تأکید"),
                Option("qualified", "مقید/با شرط", veto=True),
                Option("going_concern", "شک در تداوم فعالیت", veto=True),
                Option(UNKNOWN, "نخوانده‌ام", veto=True)),
       evidence=("codal.audit_status",)),
    _q("PB-016", 1, "آیا زیان انباشته به بیش از نصف سرمایه رسیده (ماده ۱۴۱)؟",
       "yes_no_unknown", stopper=True, options=_YES_NO, veto_values=("yes",),
       hint="«بله» یعنی رد؛ در این حالت تحلیلی ادامه نمی‌یابد.",
       note_required=True),
    _q("PB-017", 1, "سود شرکت از فعالیت اصلی می‌آید یا از فروش دارایی، تسعیر و اقلام اتفاقی؟",
       "choice",
       options=(Option("main", "از فعالیت اصلی"), Option("one_off", "از اقلام یک‌باره", veto=True),
                Option("mixed", "ترکیبی — باید نرمال‌سازی شود"),
                Option(UNKNOWN, "نمی‌دانم", veto=True)),
       evidence=("fin.net_profit_growth", "fin.earnings_quality")),
    _q("PB-018", 1, "تابلوی نماد چیست (اصلی/فرعی/پایه/شفاف/نوآر) و ریسک آن تابلو را می‌پذیرم؟",
       "choice",
       options=(Option("accept", "می‌پذیرم"), Option("not_accept", "نمی‌پذیرم", veto=True),
                Option(UNKNOWN, "نمی‌دانم", veto=True)),
       evidence=("detail.board", "detail.state")),
    _q("PB-019", 1, "نماد سابقه توقف‌های طولانی دارد؟",
       "yes_no_unknown", options=_YES_NO,
       hint="توقف طولانی یعنی نقدشوندگی روزِ نیاز، نه امروز."),
    _q("PB-020", 1, "آیا دلیلی برای خرید این سهم به‌جای هم‌گروه‌هایش وجود دارد، یا فقط «اسمش سر زبان» است؟",
       "yes_no_unknown", options=_YES_NO, golden=True, note_required=True,
       evidence=("detail.pe", "detail.group_pe"),
       hint="اگر «بله» است، دلیلش را همین‌جا بنویس."),

    # ══════════════ مرحله ۲ — کسب‌وکار و صنعت (۱۰) ══════════════
    _q("PB-021", 2, "منابع اصلی درآمد شرکت کدام‌اند و سهم هر کدام چقدر است؟", "text",
       note_required=True),
    _q("PB-022", 2, "مشتریان واقعی شرکت چه کسانی‌اند؟ وابستگی به چند مشتری بزرگ هست؟", "text"),
    _q("PB-023", 2, "رقبای اصلی کیستند و مزیت پایدار شرکت نسبت به آن‌ها چیست؟", "text",
       note_required=True),
    _q("PB-024", 2, "صنعت در چه مرحله‌ای است: رشد، بلوغ، افول؟ الان کجای چرخه رونق/رکود؟",
       "choice",
       options=(Option("growth", "رشد"), Option("mature", "بلوغ"), Option("decline", "افول", veto=True),
                Option(UNKNOWN, "نمی‌دانم", veto=True))),
    _q("PB-025", 2, "ظرفیت مازاد در صنعت وجود دارد؟ رقبای جدید چه چیزی مانع ورودشان است؟", "text"),
    _q("PB-026", 2, "آیا شرکت می‌تواند بدون افت شدید فروش قیمت‌ها را بالا ببرد؟",
       "yes_no_unknown", options=_YES_NO,
       hint="قدرت قیمت‌گذاری؛ در ایران با قیمت دستوری قیود دارد."),
    _q("PB-027", 2, "تهدید محصول جایگزین یا فناوری جدید چیست؟", "text"),
    _q("PB-028", 2, "مواد اولیه از کجا می‌آید؟ وابستگی به یک تأمین‌کننده هست؟", "text"),
    _q("PB-029", 2, "سهم بازار شرکت روند رو به رشد دارد یا افت؟", "choice",
       options=(Option("up", "رو به رشد"), Option("flat", "ثابت"),
                Option("down", "رو به افت", veto=True), Option(UNKNOWN, "نمی‌دانم", veto=True))),
    _q("PB-030", 2, "چرا این صنعت را به جایگزین‌هایش ترجیح می‌دهم — و این دلیل مکتوب است؟",
       "text", note_required=True),

    # ══════════════ مرحله ۳ — کیفیت مالی (۱۵) ══════════════
    _q("PB-031", 3, "رشد فروش از رشد مقدار بوده یا فقط از نرخ؟", "choice",
       options=(Option("volume", "رشد مقدار"), Option("price", "فقط نرخ", veto=True),
                Option("both", "هر دو"), Option(UNKNOWN, "نمی‌دانم", veto=True)),
       evidence=("fin.revenue_growth",)),
    _q("PB-032", 3, "روند حاشیه سود ناخالص/عملیاتی/خالص در ۳–۵ سال چیست و چرا با رقبا فرق دارد؟",
       "text", evidence=("fin.gross_margin", "fin.net_margin")),
    _q("PB-033", 3, "هزینه‌ها (مواد، انرژی، دستمزد) سریع‌تر از درآمد رشد نکرده‌اند؟",
       "yes_no_unknown", options=_YES_NO,
       hint="«بله» یعنی حاشیه زیر فشار است."),
    _q("PB-034", 3, "جریان نقد عملیاتی با سود خالص همخوان است؟ اگر نه، پول کجا مانده؟",
       "text", evidence=("fin.earnings_quality",)),
    _q("PB-035", 3, "عمر مطالبات تجاری چقدر است؟ ذخیره مطالبات مشکوک‌الوصول کفایت می‌کند؟",
       "number", inputs=(_I("receivable_days", "عمر مطالبات", "روز", min=0, max=3650),)),
    _q("PB-036", 3, "موجودی کالا راکد یا کم‌گردش داریم؟", "yes_no_unknown", options=_YES_NO),
    _q("PB-037", 3, "جمع بدهی، سررسیدها، نرخ‌ها و وثایق چیست؟ توان پوشش هزینه مالی چقدر است؟",
       "text", note_required=True, evidence=("fin.debt_to_equity",)),
    _q("PB-038", 3, "نسبت جاری و آنی نسبت به هم‌گروه‌ها چطور است؟", "choice",
       options=(Option("strong", "قوی‌تر"), Option("peer", "هم‌سطح"),
                Option("weak", "ضعیف‌تر", veto=True), Option(UNKNOWN, "نمی‌دانم", veto=True)),
       evidence=("fin.current_ratio",)),
    _q("PB-039", 3, "برای رشد فروش، چقدر سرمایه در گردش جدید لازم است و از کجا می‌آید؟", "text"),
    _q("PB-040", 3, "سود «نرمال‌شده» (بدون اقلام یک‌باره) چقدر است؟", "text", note_required=True),
    _q("PB-041", 3, "روند جریان نقد آزاد چیست؟ سود نقدی از عملیات پرداخت می‌شود یا از استقراض/فروش دارایی؟",
       "choice",
       options=(Option("operations", "از عملیات"), Option("debt_or_assets", "از استقراض/فروش دارایی", veto=True),
                Option("no_cash_div", "سود نقدی نداریم"), Option(UNKNOWN, "نمی‌دانم", veto=True)),
       evidence=("div.last_date",)),
    _q("PB-042", 3, "دوپونت: رشد ROE از حاشیه سود آمده، گردش دارایی، یا فقط بدهی بیشتر؟",
       "choice",
       options=(Option("margin", "حاشیه"), Option("turnover", "گردش دارایی"),
                Option("leverage", "فقط اهرم/بدهی", veto=True), Option(UNKNOWN, "نمی‌دانم", veto=True)),
       evidence=("fin.roe", "fin.asset_turnover", "fin.debt_to_equity")),
    _q("PB-043", 3, "ROIC بالاتر از هزینه سرمایه است؟", "yes_no_unknown", options=_YES_NO,
       hint="اگر نه، رشد ارزش‌آفرینی نیست."),
    _q("PB-044", 3, "تعهدات خارج از ترازنامه (ضمانت‌نامه‌ها، دعاوی، بدهی مالیاتی حل‌نشده) چیست؟",
       "text", evidence=("fin.forensic_risk",)),
    _q("PB-045", 3, "شرکت زیرمجموعه‌های مهم دارد؟ اعداد تلفیقی را با اصلی اشتباه نمی‌کنم؟",
       "yes_no_unknown", options=_YES_NO),

    # ══════════════ مرحله ۴ — سؤالات خاص ایران (۱۵) ══════════════
    _q("PB-046", 4, "محصولات شرکت مشمول قیمت‌گذاری دستوری‌اند؟ نرخ‌گذار کیست؟", "choice",
       stopper=True,
       options=(Option("free", "دستوری نیست"), Option("regulated_known", "دستوری است و نرخ‌گذار را می‌دانم"),
                Option("regulated_unknown", "دستوری است ولی نرخ‌گذار/مکانیزم را نمی‌دانم", veto=True),
                Option(UNKNOWN, "نمی‌دانم", veto=True))),
    _q("PB-047", 4, "سابقه تعدیل نرخ‌ها با تورم همگام بوده یا عقب مانده؟ شکاف قیمت مصوب و بازار موازی چقدر است؟",
       "choice", stopper=True,
       options=(Option("in_sync", "همگام"), Option("lagging", "عقب مانده", veto=True),
                Option(UNKNOWN, "نمی‌دانم", veto=True)),
       note_required=True),
    _q("PB-048", 4, "مواجهه ارزی خالص: چند درصد درآمد ارزی و چند درصد هزینه ارزی؟", "number",
       inputs=(_I("revenue_fx_pct", "درآمد ارزی", "٪", min=0, max=100),
               _I("cost_fx_pct", "هزینه ارزی", "٪", min=0, max=100),)),
    _q("PB-049", 4, "الزام برگشت ارز صادراتی و مسیر پول چگونه بر جریان نقد اثر می‌گذارد؟", "text"),
    _q("PB-050", 4, "سهمیه ارز/انرژی شرکت هست؟ سناریوی حذف سهمیه چه اثری دارد؟", "text"),
    _q("PB-051", 4, "ریسک گاز/برق در زمستان و تابستان برای تولید این شرکت چقدر است؟", "choice",
       options=(Option("low", "کم"), Option("medium", "متوسط"), Option("high", "زیاد"),
                Option(UNKNOWN, "نمی‌دانم", veto=True))),
    _q("PB-052", 4, "اثر تحریم بر فروش، تأمین مواد، و مطالبات صادراتی چیست؟", "text"),
    _q("PB-053", 4, "شناور واقعی چند است؟ (درصد رسمی در برابر گردش واقعی روزانه)", "number",
       inputs=(_I("free_float_real_pct", "شناور واقعی", "٪", min=0, max=100),),
       evidence=("detail.free_float",)),
    _q("PB-054", 4, "سهامدار عمده کیست — دولتی/بنیادی/خصوصی؟ انگیزه‌اش با من یکی است؟", "choice",
       options=(Option("aligned", "هم‌سو"), Option("neutral", "بی‌طرف"),
                Option("conflict", "در تضاد", veto=True), Option(UNKNOWN, "نمی‌دانم", veto=True)),
       evidence=("holders.top_name", "holders.top_pct", "holders.institutional_pct")),
    _q("PB-055", 4, "تعداد سهام دقیق فعلی چند است؟ افزایش سرمایه‌ای در جریان هست؟", "number",
       stopper=True,
       inputs=(_I("shares_now", "تعداد سهام", "سهم", role="shares_now", min=0),),
       evidence=("detail.shares_count",), note_required=True),
    _q("PB-056", 4, "EPS منابع مختلف بر کدام مبنای سهام محاسبه شده — قبل یا بعد از افزایش سرمایه؟",
       "choice", stopper=True,
       options=(Option("post", "بعد از افزایش سرمایه"), Option("pre", "قبل از افزایش سرمایه", veto=True),
                Option(UNKNOWN, "نمی‌دانم", veto=True)),
       evidence=("detail.eps",),
       hint="مبنای اشتباه، P/E را چند درصد جابه‌جا می‌کند."),
    _q("PB-057", 4, "چه رویداد تقویمی نزدیکی وجود دارد: مجمع، گزارش، شمولیت، سررسید اوراق؟",
       "text", evidence=("codal.last_report",)),
    _q("PB-058", 4, "عرضه ثانویه یا فروش سهام دولت/بنیاد در راه است (فشار عرضه آینده)؟",
       "yes_no_unknown", options=_YES_NO),
    _q("PB-059", 4, "بخشنامه/مقرراتی در حال تصویب هست که فردا این تحلیل را عوض کند؟",
       "yes_no_unknown", options=_YES_NO, golden=True,
       hint="«نمی‌دانم» در این سؤال یعنی تحلیل شکننده است."),
    _q("PB-060", 4, "این شرکت در برابر جهش ارزی و سقوط ارزی چه اتفاقی می‌افتد — هر دو سناریو را نوشته‌ام؟",
       "yes_no_unknown", options=_YES_NO, note_required=True),

    # ══════════════ مرحله ۵ — ارزش‌گذاری (۱۲) ══════════════
    _q("PB-061", 5, "روش ارزش‌گذاری متناسب این نوع شرکت چیست؟ (P/E سود پایدار / NAV / جریان نقد / حالت خاص زیان‌ده)",
       "choice",
       options=(Option("pe", "P/E سود پایدار"), Option("nav", "NAV"), Option("dcf", "جریان نقد"),
                Option("special", "حالت خاص (زیان‌ده/دارایی‌محور)"),
                Option(UNKNOWN, "انتخاب نکرده‌ام", veto=True))),
    _q("PB-062", 5, "EPS مبنای من از صورت مالی حسابرسی‌شده استخراج شده یا از برآورد سایت‌ها؟",
       "choice",
       options=(Option("audited", "صورت مالی حسابرسی‌شده"),
                Option("site_estimate", "برآورد سایت‌ها", veto=True),
                Option(UNKNOWN, "نمی‌دانم", veto=True)),
       evidence=("detail.eps",), note_required=True),
    _q("PB-063", 5, "P/E مناسب برای این شرکت با این کیفیت و این ریسک چقدر است — و چرا؟", "number",
       inputs=(_I("fair_pe", "P/E موجه", "برابر", min=0, max=200),),
       evidence=("detail.pe", "detail.group_pe"), note_required=True),
    _q("PB-064", 5, "محدوده ارزش (کف تا سقف) چیست — نه یک عدد دقیق؟", "number",
       inputs=(_I("value_low", "کف ارزش", "ریال", role="value_low", min=0),
               _I("value_high", "سقف ارزش", "ریال", role="value_high", min=0),),
       evidence=("detail.price_last",)),
    _q("PB-065", 5, "سناریوی بدبینانه، میانه و خوش‌بینانه سود چقدرند و مفروضاتشان سازگارند؟", "number",
       inputs=(_I("eps_pess", "EPS بدبینانه", "ریال", min=0),
               _I("eps_mid", "EPS میانه", "ریال", min=0),
               _I("eps_opt", "EPS خوش‌بینانه", "ریال", min=0),)),
    _q("PB-066", 5, "در سناریوی بدبینانه، قیمت منصفانه کجاست و قیمت فعلی چقدر پایین‌تر/بالاتر است؟",
       "number", inputs=(_I("pess_value", "ارزش بدبینانه", "ریال", role="pess_value", min=0),),
       evidence=("detail.price_last",), note_required=True),
    _q("PB-067", 5, "قیمت فعلی کجای محدوده ارزش است؟", "choice",
       options=(Option("below", "زیر کف"), Option("low_band", "نزدیک کف"), Option("mid", "میانه"),
                Option("high_band", "نزدیک سقف"), Option("above", "بالای سقف", veto=True),
                Option(UNKNOWN, "نمی‌دانم", veto=True)),
       evidence=("detail.price_last", "detail.price_min_year", "detail.price_max_year")),
    _q("PB-068", 5, "حاشیه اطمینان من چند درصد است و آیا قیمت به آن رسیده؟", "number",
       inputs=(_I("mos_pct", "حاشیه اطمینان", "٪", role="margin_of_safety_pct", min=0, max=100),),
       golden=True, note_required=True),
    _q("PB-069", 5, "گزینه‌های جایگزین (سپرده، اوراق دولتی، هم‌گروه، صندوق) با ریسک مشابه چه بازدهی می‌دهند؟",
       "text", note_required=True),
    _q("PB-070", 5, "اگر خرید فقط در سناریوی خوش‌بینانه توجیه دارد، آیا باید رد نکنم؟", "choice",
       stopper=True,
       options=(Option("also_pess", "در بدبینانه/میانه هم توجیه دارد"),
                Option("only_opt_reject", "فقط خوش‌بینانه — رد می‌کنم", veto=True),
                Option(UNKNOWN, "بررسی نکرده‌ام", veto=True))),
    _q("PB-071", 5, "در شرکت چرخه‌ای، آیا سود اوج چرخه را به‌عنوان سود دائمی فرض نکرده‌ام؟",
       "yes_no_unknown", options=_YES_NO, hint="«بله» یعنی خطای محاسباتی."),
    _q("PB-072", 5, "در هلدینگ، NAV با کسر بدهی و کیفیت دارایی حساب شده؟ تخفیف هلدینگ را خودکار آربیتراژ نگرفته‌ام؟",
       "yes_no_unknown", options=_YES_NO),

    # ══════════════ مرحله ۶ — محرک و زمان‌بندی (۷) ══════════════
    _q("PB-073", 6, "محرک مشخصی که فاصله قیمت تا ارزش را ببندد، چیست؟", "text",
       stopper=True, note_required=True, golden=False),
    _q("PB-074", 6, "زمان تقریبی تحقق آن کی است؟", "number",
       inputs=(_I("catalyst_months", "ماه تا تحقق", "ماه", min=0, max=120),)),
    _q("PB-075", 6, "چه شواهد قابل‌مشاهده‌ای نشان می‌دهد محرک در حال تحقق است؟", "text",
       note_required=True),
    _q("PB-076", 6, "این خبر/انتظار چقدر در قیمت فعلی لحاظ شده؟", "choice",
       options=(Option("fully", "کاملاً لحاظ شده", veto=True), Option("partly", "قسمتی"),
                Option("little", "تقریباً لحاظ نشده"), Option(UNKNOWN, "نمی‌دانم", veto=True)),
       evidence=("detail.price_last", "detail.pe", "detail.group_pe", "flow.real_net")),
    _q("PB-077", 6, "اگر محرک ۶ ماه عقب بیفتد چه می‌کنم؟", "choice",
       options=(Option("written_plan", "برنامهٔ نوشته‌شده دارم"), Option("hold", "نگه می‌دارم"),
                Option("exit", "می‌فروشم"), Option(UNKNOWN, "تصمیم نگرفته‌ام", veto=True))),
    _q("PB-078", 6, "هزینه فرصت انتظار چقدر است؟", "text"),
    _q("PB-079", 6, "حد زمانی بازبینی یا خروج از قبل تعیین شده؟", "yes_no_unknown", options=_YES_NO),

    # ══════════════ مرحله ۷ — تکنیکال و اجرای سفارش (۱۱) ══════════════
    _q("PB-080", 7, "روند تایم‌فریم بالاتر صعودی است، نزولی یا خنثی — و با افق من هماهنگ است؟",
       "choice",
       options=(Option("up_aligned", "صعودی و هم‌افق"), Option("up_mismatch", "صعودی ولی بی‌ارتباط با افق"),
                Option("down", "نزولی", veto=True), Option("flat", "خنثی"),
                Option(UNKNOWN, "ندیده‌ام", veto=True)),
       evidence=("detail.price_last", "detail.price_min_year", "detail.price_max_year", "signal.composite")),
    _q("PB-081", 7, "حمایت و مقاومت را به‌صورت ناحیه مشخص کرده‌ام؟", "number",
       inputs=(_I("support", "ناحیه حمایت", "ریال", min=0),
               _I("resistance", "ناحیه مقاومت", "ریال", min=0),),
       note_required=True),
    _q("PB-082", 7, "حرکت اخیر حجم پایدار داشته یا مقطعی؟", "yes_no_unknown", options=_YES_NO,
       hint="«پایدار» = بله؛ حرکت مقطعی یعنی «خیر».",
       evidence=("detail.trade_value", "detail.avg_volume_month", "detail.base_volume")),
    _q("PB-083", 7, "قیمت فعلی کجای ناحیه خرید برنامه‌ریزی‌شده کجاست؟", "number",
       inputs=(_I("zone_low", "کف ناحیه خرید", "ریال", min=0),
               _I("zone_high", "سقف ناحیه خرید", "ریال", min=0),),
       evidence=("detail.price_last",)),
    _q("PB-084", 7, "فاصله ورود تا حد ابطال چند درصد است؟ نسبت سود به زیان چقدر می‌شود؟", "number",
       inputs=(_I("entry", "قیمت ورود", "ریال", role="entry_price", min=0),
               _I("stop", "قیمت حد ابطال", "ریال", role="stop_price", min=0),
               _I("target", "قیمت هدف", "ریال", role="target_price", min=0),),
       note_required=True, hint="اگر ورود و ابطال را بدهی، فاصله و R/R محاسبه می‌شود."),
    _q("PB-085", 7, "آیا دارم صرفاً به‌خاطر رشد قیمت تعقیب می‌کنم؟", "yes_no_unknown",
       options=_YES_NO, hint="«بله» = ورود بدون مزیت تحلیلی."),
    _q("PB-086", 7, "حجم مبنا، دامنه نوسان و وضعیت صف امروز را چک کرده‌ام؟", "yes_no_unknown",
       options=_YES_NO,
       evidence=("detail.base_volume", "detail.tmin", "detail.tmax", "queue.status")),
    _q("PB-087", 7, "صف خرید/فروش اثر اجرای سفارشم را چه می‌کند؟", "text",
       evidence=("queue.status", "queue.days", "queue.distance")),
    _q("PB-088", 7, "لغزش قیمت و کارمزد+مالیات در محاسبه سودم هست؟", "number",
       inputs=(_I("slippage_pct", "لغزش", "٪", min=0, max=50),
               _I("fee_pct", "کارمزد", "٪", min=0, max=50),
               _I("tax_pct", "مالیات", "٪", min=0, max=50),),
       note_required=True),
    _q("PB-089", 7, "سهمیه زمانی/سفارشی کارگزاری‌ام برای این اندازه سفارش کافی است؟",
       "yes_no_unknown", options=_YES_NO),
    _q("PB-090", 7, "روز اختلال سامانه، مسیر جایگزین معاملاتی دارم؟", "yes_no_unknown",
       options=_YES_NO),

    # ══════════════ مرحله ۸ — اندازه موقعیت و ریسک سبد (۸) ══════════════
    _q("PB-091", 8, "طبق فرمول (زیان مجاز ÷ فاصله تا حد خروج) اندازه موقعیت چقدر می‌شود؟", "number",
       inputs=(_I("position_toman", "اندازه موقعیت", "تومان", role="position_size_toman", min=0),),
       golden=True,
       hint="عدد خودت را بده؛ با مقدار محاسبه‌شده از فرمول مقایسه می‌شود."),
    _q("PB-092", 8, "این عدد با سقف وزن سهم/صنعت تطبیق دارد؟", "yes_no_unknown", options=_YES_NO,
       hint="تعارض با سقف وزن به‌صورت خودکار نمایش داده می‌شود."),
    _q("PB-093", 8, "با نقدشوندگی واقعی سهم تطبیق دارد؟ زمان خروج کامل چقدر است؟", "text",
       evidence=("detail.trade_value", "detail.avg_volume_month", "detail.free_float")),
    _q("PB-094", 8, "مجموع ریسک موقعیت‌های باز سبد چقدر می‌شود با اضافه‌شدن این معامله؟", "number",
       inputs=(_I("open_risk_pct", "مجموع ریسک باز", "٪", role="open_risk_pct", min=0, max=500),)),
    _q("PB-095", 8, "همبستگی این سهم با بقیه سبد (ارز، کالا، صنعت) چیست؟ تمرکز پنهان دارم؟", "text",
       note_required=True, evidence=("detail.sector",)),
    _q("PB-096", 8, "برنامه خرید پله‌ای دارم؟ شرط هر پله مستقل از صرفاً افت قیمت چیست؟", "choice",
       options=(Option("written", "دارم و نوشته‌ام"), Option("none", "ندارم", veto=True),
                Option(UNKNOWN, "نمی‌دانم", veto=True)),
       note_required=True),
    _q("PB-097", 8, "اگر هم‌زمان چند حد خروج فعال شود، کل افت سبد چقدر می‌شود؟", "number",
       inputs=(_I("worst_pct", "بدترین افت هم‌زمان سبد", "٪", role="worst_case_pct", min=0, max=100),)),
    _q("PB-098", 8, "سناریوی صف فروش چندروزه: خروج من اصلاً چطور اجرا می‌شود؟", "yes_no_unknown",
       stopper=True, options=_YES_NO, veto_values=("no",), note_required=True,
       evidence=("queue.status", "detail.base_volume", "detail.trade_value")),

    # ══════════════ مرحله ۹ — طرح فروش (۷) ══════════════
    _q("PB-099", 9, "دقیقاً چه چیزی فرض اصلی خریدم را باطل می‌کند؟ (شرط ابطال تحلیل)", "text",
       stopper=True, note_required=True, golden=True,
       hint="باید یک رویداد/عدد قابل‌مشاهده باشد، نه «اگر بد شد»."),
    _q("PB-100", 9, "در چه قیمتی یا با چه اتفاقی می‌فروشم — از پیش نوشته‌ام؟", "text",
       note_required=True),
    _q("PB-101", 9, "هدف قیمتی و حد زمانی نگهداری چیست؟", "number",
       inputs=(_I("target_uplift_pct", "هدف صعود", "٪", role="target_uplift_pct", min=0, max=2000),
               _I("hold_months", "حداکثر ماه نگهداری", "ماه", role="hold_months", min=0, max=600),)),
    _q("PB-102", 9, "اگر سود کرد چه می‌کنم؟ (سقف برداشت سود پله‌ای نوشته‌ام؟)", "yes_no_unknown",
       options=_YES_NO, note_required=True),
    _q("PB-103", 9, "اگر زیان کرد چه می‌کنم؟ (حد خروج را بعداً دورتر نمی‌برم؟)", "yes_no_unknown",
       options=_YES_NO, note_required=True),
    _q("PB-104", 9, "اگر گزارش فصلی ضعیف بود، چطور «ضعف مقطعی» را از «افت ساختاری» جدا می‌کنم؟",
       "choice",
       options=(Option("criteria", "ملاک نوشته‌شده دارم"),
                Option("price_only", "فقط با قیمت قضاوت می‌کنم", veto=True),
                Option(UNKNOWN, "ندارم", veto=True))),
    _q("PB-105", 9, "تاریخ بازبینی بعدی این تحلیل کی است؟", "number",
       inputs=(_I("review_days", "بازبینی پس از", "روز", role="review_days", min=1, max=730),),
       note_required=True),

    # ══════════════ مرحله ۱۰ — خودکنترلی نهایی (۱۰) ══════════════
    _q("PB-106", 10, "آیا دلیلی برای خرید دارم جز این‌که «دیر رسیده‌ام» یا «همه دارند می‌خرند»؟",
       "yes_no_unknown", options=_YES_NO),
    _q("PB-107", 10, "آیا عمداً شواهد مخالف خرید را جست‌وجو کرده‌ام؟", "yes_no_unknown", options=_YES_NO),
    _q("PB-108", 10, "آیا این ایده به کانال/شایعه/دوست وابسته است، یا خودم به سند اولیه وصلش کرده‌ام؟",
       "choice",
       options=(Option("primary", "از سند اولیه (کدال/صورت مالی)"),
                Option("rumor", "از کانال/شایعه/دوست", veto=True),
                Option("mixed", "ترکیبی — منبع اولیه ضعیف است", veto=True),
                Option(UNKNOWN, "نمی‌دانم", veto=True))),
    _q("PB-109", 10, "آیا به قیمت خرید یا سقف تاریخی سهم لنگر انداخته‌ام؟", "yes_no_unknown",
       options=_YES_NO,
       evidence=("detail.price_last", "detail.price_min_year", "detail.price_max_year")),
    _q("PB-110", 10, "آیا برگه تصمیم کامل پر شده؟", "yes_no_unknown", options=_YES_NO,
       hint="وضعیت تکمیل‌بودن به‌صورت خودکار محاسبه و نمایش داده می‌شود."),
    _q("PB-111", 10, "می‌توانم دلیل خرید را در دو جمله برای یک شخص بی‌طرف توضیح دهم؟", "text",
       note_required=True),
    _q("PB-112", 10, "اگر فردا ۲۰٪ سقوط کند، واکنش نوشته‌شده‌ام چیست — و خواب راحت می‌برم؟", "text",
       note_required=True),
    _q("PB-113", 10, "آیا دارم با پولی که نباید، یا برای جبران زیان معامله قبلی، می‌خرم؟",
       "yes_no_unknown", stopper=True, options=_YES_NO, veto_values=("yes",),
       hint="«بله» در این سؤال، معامله را بدون بحث لغو می‌کند."),
    _q("PB-114", 10, "آیا این خرید فقط برای این است که نقد بی‌کار در حساب دارم؟",
       "yes_no_unknown", options=_YES_NO),
    _q("PB-115", 10, "اگر امروز تحلیل را پنهان کنم و یک سال بعد ببینم، از تصمیمم دفاع می‌کنم؟",
       "text", note_required=True),
)

GOLDEN_CODES: tuple[str, ...] = tuple(q.code for q in _QUESTIONS if q.golden)
STOPPER_CODES: tuple[str, ...] = tuple(q.code for q in _QUESTIONS if q.stopper)
EVIDENCE_KEYS: frozenset[str] = frozenset(_E)

#: Stage-8 / stage-7 numeric answers the derived maths reads.
ROLLED_ROLES: frozenset[str] = frozenset(
    inp.role for q in _QUESTIONS for inp in q.inputs if inp.role
)


def stages() -> tuple[Stage, ...]:
    return _STAGES


def evidence_by_key() -> dict[str, Evidence]:
    """The evidence catalogue — the resolver's contract, so labels live in one place."""
    return dict(_E)


def questions() -> tuple[Question, ...]:
    return _QUESTIONS


def questions_by_stage(stage_id: int) -> tuple[Question, ...]:
    return tuple(q for q in _QUESTIONS if q.stage == stage_id)


def question(code: str) -> Question | None:
    return next((q for q in _QUESTIONS if q.code == code), None)


__all__ = [
    "GOLDEN_CODES",
    "ROLLED_ROLES",
    "STOPPER_CODES",
    "evidence_by_key",
    "question",
    "questions",
    "questions_by_stage",
    "stages",
]
