from __future__ import annotations

from dataclasses import dataclass


@dataclass
class IndicatorSpec:
    id: str
    group: str
    function_name: str
    inputs: list[str]
    formula: str
    python_formula: str
    pseudo_code: str = ""
    interpretation: str = ""
    rule_of_thumb: str = ""
    use_case: str = ""
    caveat: str = ""


ALL_SPECS: list[IndicatorSpec] = [
    # ── General ──────────────────────────────────────────────────
    IndicatorSpec(
        id="simple_return",
        group="general",
        function_name="calculate_simple_return",
        inputs=["price_t", "price_t_minus_1"],
        formula="R_t = (P_t - P_{t-1}) / P_{t-1}",
        python_formula="(price_t - price_t_minus_1) / price_t_minus_1",
        pseudo_code="return (price_t - price_t_minus_1) / price_t_minus_1",
        interpretation="تغییر نسبی قیمت",
        rule_of_thumb="وابسته به دارایی و بازه زمانی",
        use_case="محاسبه بازده پایه",
        caveat="برای مقایسه بین دارایی‌های با نوسان ساختاری متفاوت کافی نیست",
    ),
    IndicatorSpec(
        id="log_return",
        group="general",
        function_name="calculate_log_return",
        inputs=["price_t", "price_t_minus_1"],
        formula="r_t = ln(P_t / P_{t-1})",
        python_formula="math.log(price_t / price_t_minus_1)",
        pseudo_code="return ln(price_t / price_t_minus_1)",
        interpretation="بازده مناسب مدل‌سازی آماری",
        rule_of_thumb="برای سری‌های زمانی و مدل‌های کمی مناسب‌تر است",
        use_case="feature engineering, regression, volatility modeling",
        caveat="برای گزارش کاربر نهایی معمولاً بازده ساده شهودی‌تر است",
    ),
    IndicatorSpec(
        id="daily_range",
        group="general",
        function_name="calculate_daily_range",
        inputs=["high_t", "low_t"],
        formula="Range_t = H_t - L_t",
        python_formula="high_t - low_t",
        pseudo_code="return high_t - low_t",
        interpretation="نوسان خام روز",
        rule_of_thumb="بالاتر = بی‌ثباتی بیشتر",
        use_case="تشخیص روزهای پرتنش",
        caveat="بدون نرمال‌سازی نسبت به قیمت قابل مقایسه بین نمادها نیست",
    ),
    IndicatorSpec(
        id="relative_range",
        group="general",
        function_name="calculate_relative_range",
        inputs=["high_t", "low_t", "close_t_minus_1"],
        formula="RangePct_t = (H_t - L_t) / C_{t-1}",
        python_formula="(high_t - low_t) / close_t_minus_1",
        pseudo_code="return (high_t - low_t) / close_t_minus_1",
        interpretation="دامنه نرمال‌شده نسبت به قیمت",
        rule_of_thumb="بالاتر = نوسان بیشتر",
        use_case="مقایسه بین چند دارایی",
        caveat="قوانین دامنه نوسان یا توقف نماد می‌تواند مقایسه را مخدوش کند",
    ),
    IndicatorSpec(
        id="clv",
        group="general",
        function_name="calculate_clv",
        inputs=["close_t", "high_t", "low_t"],
        formula="CLV_t = (2*C_t - H_t - L_t) / (H_t - L_t)",
        python_formula="(2 * close_t - high_t - low_t) / (high_t - low_t)",
        pseudo_code="if high_t == low_t: return 0.0; return (2*close_t - high_t - low_t)/(high_t - low_t)",
        interpretation="محل بسته‌شدن نسبت به دامنه روز",
        rule_of_thumb="> 0.5 خوب, < -0.5 ضعیف",
        use_case="کیفیت کندل",
        caveat="بدون لحاظ حجم، قدرت حرکت را کامل نشان نمی‌دهد",
    ),
    IndicatorSpec(
        id="recovery_ratio",
        group="general",
        function_name="calculate_recovery_ratio",
        inputs=["close_t", "high_t", "low_t"],
        formula="Recovery_t = (C_t - L_t) / (H_t - L_t)",
        python_formula="(close_t - low_t) / (high_t - low_t)",
        pseudo_code="if high_t == low_t: return 0.0; return (close_t - low_t)/(high_t - low_t)",
        interpretation="میزان برگشت قیمت از کف روز",
        rule_of_thumb="بالاتر بهتر",
        use_case="تشخیص جذب فروش",
        caveat="سیگنال قطعی خرید نیست",
    ),
    IndicatorSpec(
        id="relative_volume",
        group="general",
        function_name="calculate_relative_volume",
        inputs=["volume_t", "avg_volume_n"],
        formula="RVOL_t = V_t / mean(V, n)",
        python_formula="volume_t / avg_volume_n",
        pseudo_code="return volume_t / avg_volume_n",
        interpretation="شدت غیرعادی بودن حجم",
        rule_of_thumb="> 1.5 مهم, > 2 قوی",
        use_case="تایید حرکت",
        caveat="حجم بالا همیشه ورود پول هوشمند نیست",
    ),
    IndicatorSpec(
        id="volume_zscore",
        group="general",
        function_name="calculate_volume_zscore",
        inputs=["volume_t", "mean_volume", "std_volume"],
        formula="Z^V_t = (V_t - mu_V) / sigma_V",
        python_formula="(volume_t - mean_volume) / std_volume",
        pseudo_code="if std_volume == 0: return 0.0; return (volume_t - mean_volume) / std_volume",
        interpretation="شدت آماری انحراف حجم",
        rule_of_thumb="> 2 معنادار",
        use_case="غربال آماری",
        caveat="فرض نرمال بودن داده‌ها همیشه برقرار نیست",
    ),
    IndicatorSpec(
        id="traded_value",
        group="general",
        function_name="calculate_traded_value",
        inputs=["price_t", "volume_t"],
        formula="Value_t = P_t * V_t",
        python_formula="price_t * volume_t",
        pseudo_code="return price_t * volume_t",
        interpretation="پول جابه‌جا شده",
        rule_of_thumb="بیشتر = اعتبار بیشتر حرکت",
        use_case="غربال نقدشوندگی",
        caveat="اتکا صرف به حجم بدون ارزش معاملات خطاست",
    ),
    IndicatorSpec(
        id="float_turnover",
        group="general",
        function_name="calculate_float_turnover",
        inputs=["volume_t", "effective_float_shares"],
        formula="Turnover_t = V_t / Float",
        python_formula="volume_t / effective_float_shares",
        pseudo_code="return volume_t / effective_float_shares",
        interpretation="نسبت معامله به شناوری مؤثر",
        rule_of_thumb="بالاتر = چرخش شدیدتر",
        use_case="تشخیص انباشت/توزیع",
        caveat="استفاده از شناوری اسمی به‌جای مؤثر گمراه‌کننده است",
    ),
    IndicatorSpec(
        id="amihud_illiquidity",
        group="general",
        function_name="calculate_amihud_illiquidity",
        inputs=["return_t_abs", "traded_value_t"],
        formula="ILLIQ_t = |R_t| / Value_t",
        python_formula="abs(return_t) / traded_value_t",
        pseudo_code="if traded_value_t == 0: return None; return abs(return_t) / traded_value_t",
        interpretation="اثر قیمت به ازای هر واحد پول معامله‌شده",
        rule_of_thumb="کمتر = نقدشونده‌تر",
        use_case="سنجش نقدشوندگی",
        caveat="در نمادهای کم‌معامله به‌شدت ناپایدار می‌شود",
    ),
    IndicatorSpec(
        id="true_range",
        group="general",
        function_name="calculate_true_range",
        inputs=["high_t", "low_t", "close_t_minus_1"],
        formula="TR_t = max(H-L, |H-C_prev|, |L-C_prev|)",
        python_formula="max(high_t - low_t, abs(high_t - close_t_minus_1), abs(low_t - close_t_minus_1))",
        pseudo_code="return max(high_t - low_t, abs(high_t - close_t_minus_1), abs(low_t - close_t_minus_1))",
        interpretation="دامنه واقعی با لحاظ گپ",
        rule_of_thumb="بالاتر = نوسان بیشتر",
        use_case="پایه ATR",
        caveat="به‌تنهایی جهت حرکت را نشان نمی‌دهد",
    ),
    IndicatorSpec(
        id="atr",
        group="general",
        function_name="calculate_atr",
        inputs=["true_ranges"],
        formula="ATR_n = mean(TR, n)",
        python_formula="sum(true_ranges) / len(true_ranges)",
        pseudo_code="return average(true_ranges_last_n)",
        interpretation="نوسان میانگین",
        rule_of_thumb="بالاتر = پرنوسان‌تر",
        use_case="حد ضرر، sizing، screening",
        caveat="بین دارایی‌های با قیمت متفاوت باید نرمال‌سازی شود",
    ),
    IndicatorSpec(
        id="normalized_volatility",
        group="general",
        function_name="calculate_normalized_volatility",
        inputs=["atr_t", "close_t"],
        formula="VolNorm_t = ATR_t / C_t",
        python_formula="atr_t / close_t",
        pseudo_code="return atr_t / close_t",
        interpretation="نوسان نسبت به قیمت",
        rule_of_thumb="کمتر = آرام‌تر",
        use_case="مقایسه بین نمادها",
        caveat="باید همراه با ساختار خبری و گپ‌ها تفسیر شود",
    ),
    IndicatorSpec(
        id="compression_ratio",
        group="general",
        function_name="calculate_compression_ratio",
        inputs=["atr_short", "atr_long"],
        formula="Comp_t = ATR_short / ATR_long",
        python_formula="atr_short / atr_long",
        pseudo_code="return atr_short / atr_long",
        interpretation="فشردگی نوسان",
        rule_of_thumb="< 0.7 جالب",
        use_case="کشف pre-breakout",
        caveat="بدون جهت و قدرت نسبی کافی نیست",
    ),
    IndicatorSpec(
        id="bollinger_bandwidth",
        group="general",
        function_name="calculate_bollinger_bandwidth",
        inputs=["upper_band", "lower_band", "middle_ma"],
        formula="BBW_t = (Upper - Lower) / MA",
        python_formula="(upper_band - lower_band) / middle_ma",
        pseudo_code="return (upper_band - lower_band) / middle_ma",
        interpretation="فشردگی یا انبساط باندها",
        rule_of_thumb="صدک‌های پایین مهم‌اند",
        use_case="اسکن سکون قبل از حرکت",
        caveat="به‌تنهایی بدون حجم و RS کافی نیست",
    ),
    IndicatorSpec(
        id="relative_strength_ratio",
        group="general",
        function_name="calculate_relative_strength_ratio",
        inputs=["asset_price", "benchmark_price"],
        formula="RS_t = P_asset / P_benchmark",
        python_formula="asset_price / benchmark_price",
        pseudo_code="return asset_price / benchmark_price",
        interpretation="عملکرد نسبی نسبت به معیار",
        rule_of_thumb="روند صعودی مطلوب",
        use_case="کشف لیدر بازار",
        caveat="تمرکز صرف بر قیمت مطلق خطاست",
    ),
    IndicatorSpec(
        id="excess_return",
        group="general",
        function_name="calculate_excess_return",
        inputs=["asset_return", "benchmark_return"],
        formula="ER_t = R_asset - R_benchmark",
        python_formula="asset_return - benchmark_return",
        pseudo_code="return asset_return - benchmark_return",
        interpretation="برتری نسبت به benchmark",
        rule_of_thumb="مثبت بهتر",
        use_case="ارزیابی تاکتیکی",
        caveat="benchmark اشتباه کل تحلیل را خراب می‌کند",
    ),
    IndicatorSpec(
        id="zscore",
        group="general",
        function_name="calculate_zscore",
        inputs=["x_t", "mean_x", "std_x"],
        formula="Z_{x,t} = (x_t - mu_x) / sigma_x",
        python_formula="(x_t - mean_x) / std_x",
        pseudo_code="if std_x == 0: return 0.0; return (x_t - mean_x) / std_x",
        interpretation="نرمال‌سازی ویژگی",
        rule_of_thumb="|Z| > 2 مهم",
        use_case="ranking, anomaly detection, factor scoring",
        caveat="در توزیع‌های چوله یا heavy-tail باید robust scaling را هم بررسی کرد",
    ),
    # ── Stocks ──────────────────────────────────────────────────
    IndicatorSpec(
        id="avg_real_buy_per_capita",
        group="stocks",
        function_name="calculate_avg_real_buy_per_capita",
        inputs=["real_buy_value", "real_buy_count"],
        formula="AvgRealBuy = Val_rb / N_rb",
        python_formula="real_buy_value / real_buy_count",
        pseudo_code="return real_buy_value / real_buy_count",
        interpretation="قدرت مالی متوسط خریدار حقیقی",
        rule_of_thumb="باید نسبت به اندازه سهم و تاریخچه خودش سنجیده شود",
        use_case="کشف خریدار درشت",
        caveat="مقایسه خام بین شرکت‌های کوچک و بزرگ گمراه‌کننده است",
    ),
    IndicatorSpec(
        id="avg_real_sell_per_capita",
        group="stocks",
        function_name="calculate_avg_real_sell_per_capita",
        inputs=["real_sell_value", "real_sell_count"],
        formula="AvgRealSell = Val_rs / N_rs",
        python_formula="real_sell_value / real_sell_count",
        pseudo_code="return real_sell_value / real_sell_count",
        interpretation="قدرت مالی متوسط فروشنده حقیقی",
        rule_of_thumb="باید با buy capita و context قیمت مقایسه شود",
        use_case="تحلیل فشار فروش",
        caveat="تفسیر منفرد بدون روند و قیمت ناقص است",
    ),
    IndicatorSpec(
        id="buyer_power_ratio",
        group="stocks",
        function_name="calculate_buyer_power_ratio",
        inputs=["real_buy_value", "real_buy_count", "real_sell_value", "real_sell_count"],
        formula="BPR = (Val_rb / N_rb) / (Val_rs / N_rs)",
        python_formula="(real_buy_value / real_buy_count) / (real_sell_value / real_sell_count)",
        pseudo_code="buy_cap = real_buy_value / real_buy_count; sell_cap = real_sell_value / real_sell_count; return buy_cap / sell_cap",
        interpretation="برتری مالی خریدار نسبت به فروشنده",
        rule_of_thumb="> 1.5 خوب, > 2 قوی",
        use_case="کشف پول هوشمند",
        caveat="نزدیک مقاومت می‌تواند نشانه توزیع باشد نه انباشت",
    ),
    IndicatorSpec(
        id="net_real_money_flow",
        group="stocks",
        function_name="calculate_net_real_money_flow",
        inputs=["real_buy_value", "real_sell_value"],
        formula="NetRealFlow = Val_rb - Val_rs",
        python_formula="real_buy_value - real_sell_value",
        pseudo_code="return real_buy_value - real_sell_value",
        interpretation="جهت خالص ورود/خروج پول حقیقی",
        rule_of_thumb="مثبت بهتر",
        use_case="تشخیص انباشت",
        caveat="مثبت بودن یک‌روزه کافی نیست",
    ),
    IndicatorSpec(
        id="normalized_real_flow",
        group="stocks",
        function_name="calculate_normalized_real_flow",
        inputs=["net_real_flow", "free_float_market_cap"],
        formula="NRF = NetRealFlow / FreeFloatMcap",
        python_formula="net_real_flow / free_float_market_cap",
        pseudo_code="return net_real_flow / free_float_market_cap",
        interpretation="شدت ورود پول نسبت به اندازه سهم",
        rule_of_thumb="بالاتر بهتر",
        use_case="مقایسه بین نمادها",
        caveat="نباید از market cap کل به‌جای free float استفاده کرد",
    ),
    IndicatorSpec(
        id="ownership_change",
        group="stocks",
        function_name="calculate_ownership_change",
        inputs=["ownership_t", "ownership_t_minus_1"],
        formula="DeltaOwn_t = Own_t - Own_{t-1}",
        python_formula="ownership_t - ownership_t_minus_1",
        pseudo_code="return ownership_t - ownership_t_minus_1",
        interpretation="تغییر ساختار مالکیت",
        rule_of_thumb="روند مهم‌تر از یک مشاهده منفرد",
        use_case="تحلیل چرخش مالکیت",
        caveat="تکیه به یک روز خطاست",
    ),
    IndicatorSpec(
        id="ownership_hhi",
        group="stocks",
        function_name="calculate_ownership_hhi",
        inputs=["ownership_shares_list"],
        formula="HHI = sum(s_i^2)",
        python_formula="sum(s ** 2 for s in ownership_shares_list)",
        pseudo_code="return sum(share_i ** 2 for share_i in shares)",
        interpretation="تمرکز سهامداری",
        rule_of_thumb="بالاتر = تمرکز بیشتر",
        use_case="تشخیص float lock",
        caveat="با داده ناقص سهامداری اعتبار کم می‌شود",
    ),
    IndicatorSpec(
        id="supply_absorption_score",
        group="stocks",
        function_name="calculate_supply_absorption_score",
        inputs=["sell_pressure", "return_t", "epsilon"],
        formula="ABS_t = SellPressure_t / (|R_t| + epsilon)",
        python_formula="sell_pressure / (abs(return_t) + epsilon)",
        pseudo_code="return sell_pressure / (abs(return_t) + epsilon)",
        interpretation="فشار فروش زیاد با افت کم = جذب عرضه",
        rule_of_thumb="بالاتر = جذب بیشتر",
        use_case="تشخیص absorption",
        caveat="تعریف sell pressure باید دقیق و یکنواخت باشد",
    ),
    IndicatorSpec(
        id="supply_dryness",
        group="stocks",
        function_name="calculate_supply_dryness",
        inputs=["volume_t", "avg_volume_20"],
        formula="Dryness = 1 - (V_t / mean(V,20))",
        python_formula="1 - (volume_t / avg_volume_20)",
        pseudo_code="return 1 - (volume_t / avg_volume_20)",
        interpretation="کاهش عرضه قابل فروش",
        rule_of_thumb="بالا همراه با حفظ قیمت مثبت است",
        use_case="پیش‌درآمد شکست",
        caveat="حجم کم ناشی از بی‌علاقگی بازار را نباید با خشک‌شدن عرضه اشتباه گرفت",
    ),
    IndicatorSpec(
        id="correction_dryness_ratio",
        group="stocks",
        function_name="calculate_correction_dryness_ratio",
        inputs=["mean_volume_down_days", "mean_volume_up_days"],
        formula="CorrDry = MeanVolDown / MeanVolUp",
        python_formula="mean_volume_down_days / mean_volume_up_days",
        pseudo_code="return mean_volume_down_days / mean_volume_up_days",
        interpretation="کیفیت پولبک از منظر حجم",
        rule_of_thumb="< 1 بهتر",
        use_case="تشخیص اصلاح کم‌عرضه",
        caveat="بدون تفکیک regime بازار ناقص است",
    ),
    IndicatorSpec(
        id="distance_to_resistance",
        group="stocks",
        function_name="calculate_distance_to_resistance",
        inputs=["resistance_level", "close_t"],
        formula="DistRes = (R* - C_t) / R*",
        python_formula="(resistance_level - close_t) / resistance_level",
        pseudo_code="return (resistance_level - close_t) / resistance_level",
        interpretation="نزدیکی قیمت به مقاومت",
        rule_of_thumb="کوچک‌تر = نزدیک‌تر",
        use_case="زمان‌بندی شکست",
        caveat="بدون فیلتر شکست کاذب قابل اتکا نیست",
    ),
    IndicatorSpec(
        id="resistance_touches",
        group="stocks",
        function_name="calculate_resistance_touches",
        inputs=["high_series", "resistance_level", "delta"],
        formula="Touches = sum(1(|H_i - R*| / R* < delta))",
        python_formula="sum(1 for h in high_series if abs(h - resistance_level) / resistance_level < delta)",
        pseudo_code="count = 0; for h in highs: if abs(h - resistance_level)/resistance_level < delta: count += 1; return count",
        interpretation="دفعات تست مقاومت",
        rule_of_thumb="زیاد + افت کم = مثبت",
        use_case="بررسی فشار به سطح",
        caveat="فقط تعداد کافی نیست؛ کیفیت واکنش‌ها هم مهم است",
    ),
    IndicatorSpec(
        id="breakout_quality",
        group="stocks",
        function_name="calculate_breakout_quality",
        inputs=["z_rvol", "z_clv", "z_rs", "z_dist_res", "w1", "w2", "w3", "w4"],
        formula="BOQ = w1*Z(RVOL) + w2*Z(CLV) + w3*Z(RS) - w4*Z(DistRes)",
        python_formula="w1*z_rvol + w2*z_clv + w3*z_rs - w4*z_dist_res",
        pseudo_code="return w1*z_rvol + w2*z_clv + w3*z_rs - w4*z_dist_res",
        interpretation="قدرت نسبی شکست",
        rule_of_thumb="بالاتر بهتر",
        use_case="رتبه‌بندی شکست‌ها",
        caveat="وزن‌دهی بدون بک‌تست خطرناک است",
    ),
    IndicatorSpec(
        id="breakout_acceptance",
        group="stocks",
        function_name="calculate_breakout_acceptance",
        inputs=["future_close_series", "resistance_level"],
        formula="Acceptance = count(C_{t+i} > R*) / m",
        python_formula="sum(1 for c in future_close_series if c > resistance_level) / len(future_close_series)",
        pseudo_code="return number_of_closes_above_resistance / total_future_bars",
        interpretation="ماندگاری بالای سطح شکسته‌شده",
        rule_of_thumb="> 0.6 خوب",
        use_case="فیلتر شکست کاذب",
        caveat="نگاه فقط به روز شکست اشتباه است",
    ),
    # ── Composite ────────────────────────────────────────────────
    IndicatorSpec(
        id="stock_market_score",
        group="composite",
        function_name="calculate_stock_market_score",
        inputs=[
            "z_rvol",
            "z_bpr",
            "z_net_real_flow",
            "z_clv",
            "z_rs",
            "z_abs",
            "z_illiq",
            "w1",
            "w2",
            "w3",
            "w4",
            "w5",
            "w6",
            "w7",
        ],
        formula="Score_stock = w1*Z(RVOL)+w2*Z(BPR)+w3*Z(NetRealFlow)+w4*Z(CLV)+w5*Z(RS)+w6*Z(ABS)-w7*Z(ILLIQ)",
        python_formula="w1*z_rvol + w2*z_bpr + w3*z_net_real_flow + w4*z_clv + w5*z_rs + w6*z_abs - w7*z_illiq",
        pseudo_code="return weighted_sum_positive_factors - weighted_illiquidity_penalty",
        interpretation="امتیاز نهایی کیفیت setup سهام",
        rule_of_thumb="بالاتر بهتر",
        use_case="ranking و screener",
        caveat="باید با بک‌تست و نرمال‌سازی مناسب وزن‌دهی شود",
    ),
]


def get_spec_by_id(spec_id: str) -> IndicatorSpec | None:
    return next((s for s in ALL_SPECS if s.id == spec_id), None)


def get_specs_by_group(group: str) -> list[IndicatorSpec]:
    return [s for s in ALL_SPECS if s.group == group]
