"""Currency domain — pure dataclasses + business rules, no I/O."""

from .entities import (
    ArbitrageRow,
    AssetType,
    Confidence,
    KillSwitch,
    ManualPosition,
    MarketSummary,
    PositionPnL,
    RatePair,
    RateSnapshot,
    RiskLevel,
    Signal,
    SignalType,
)
from .kill_switch import (
    BUBBLE_LIMIT,
    HOURLY_LIMIT,
    SPREAD_LIMIT,
    TETHER_ARB_LIMIT,
    VOLATILITY_LIMIT,
    check_kill_switch,
)
from .pricing import (
    arbitrage_status_for,
    bubble_index,
    classify_sentiment,
    daily_volatility_pct,
    position_pnl_toman,
    simple_return_pct,
    spread_pct,
    tether_arbitrage_pct,
)
from .signals import generate_signals

__all__ = [
    "ArbitrageRow",
    "AssetType",
    "BUBBLE_LIMIT",
    "Confidence",
    "HOURLY_LIMIT",
    "KillSwitch",
    "ManualPosition",
    "MarketSummary",
    "PositionPnL",
    "RatePair",
    "RateSnapshot",
    "RiskLevel",
    "SPREAD_LIMIT",
    "Signal",
    "SignalType",
    "TETHER_ARB_LIMIT",
    "VOLATILITY_LIMIT",
    "arbitrage_status_for",
    "bubble_index",
    "check_kill_switch",
    "classify_sentiment",
    "daily_volatility_pct",
    "generate_signals",
    "position_pnl_toman",
    "simple_return_pct",
    "spread_pct",
    "tether_arbitrage_pct",
]
