from domain.indicators.definitions import MARKET_COMMODITY, SIGNAL_NEUTRAL, IndicatorMeta

COMMODITY_INDICATORS = [
    IndicatorMeta(
        name="dsr",
        display_name="نسبت تقاضا به عرضه (DSR)",
        category="commodity",
        subcategory="demand_supply",
        market_type=MARKET_COMMODITY,
        formula="DSR = Demand / Supply",
        formula_latex="DSR = \\frac{Demand}{Supply}",
        interpretation="مازاد تقاضا نسبت به عرضه در بورس کالا",
        threshold="> 1 مثبت، > 1.5 قوی",
        application="شناسایی بازار داغ و ناترازی",
        caveat="تقاضای صوری ممکن است آمار را مخدوش کند",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="cp",
        display_name="درصد رقابت (CP)",
        category="commodity",
        subcategory="competition",
        market_type=MARKET_COMMODITY,
        formula="CP = ((P_final - P_base) / P_base) * 100",
        formula_latex="CP = \\frac{P_{final} - P_{base}}{P_{base}} \\times 100",
        interpretation="شدت رقابت خریداران برای تصاحب کالا",
        threshold="> 5%% مهم، > 10%% داغ",
        application="پیش‌بینی سود (EPS) شرکت",
        caveat="بی‌توجهی به حجم معامله‌شده",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="dom_glob_spread",
        display_name="اسپرد داخلی-جهانی",
        category="commodity",
        subcategory="arbitrage",
        market_type=MARKET_COMMODITY,
        formula="Spread = P_dom - P_glob * FX - Cost / (P_glob * FX + Cost)",
        formula_latex="Spread = \\frac{P_{dom} - P_{glob} \\times FX - Cost}{P_{glob} \\times FX + Cost}",
        interpretation="انحراف قیمت داخلی از قیمت جهانی تعدیل‌شده با نرخ ارز",
        threshold="مثبت/منفی شدید مهم",
        application="آربیتراژ بین بازارها، ارزندگی",
        caveat="انتخاب غلط نرخ ارز یا هزینه‌ها",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="price_discovery",
        display_name="نرخ کشف قیمت",
        category="commodity",
        subcategory="competition",
        market_type=MARKET_COMMODITY,
        formula="PD = CP * ln(1 + DSR)",
        formula_latex="PD = CP \\times \\ln(1 + DSR)",
        interpretation="ترکیب رقابت و تقاضا برای کشف نرخ واقعی",
        threshold="بالاتر = داغ‌تر",
        application="رتبه‌بندی عرضه‌ها",
        caveat="اثرگذاری بیش‌ازحد در DSRهای پرت",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="gross_profit_sensitivity",
        display_name="حساسیت سود ناخالص به قیمت",
        category="commodity",
        subcategory="fundamental",
        market_type=MARKET_COMMODITY,
        formula="∂GP/∂P = q",
        formula_latex="\\frac{\\partial GP}{\\partial P} = q",
        interpretation="اثر افزایش نرخ فروش بر سود ناخالص شرکت",
        threshold="تابع مقدار فروش",
        application="تحلیل بنیادی سودآوری",
        caveat="فرض ثبات کامل مقدار فروش",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="fill_rate",
        display_name="نرخ معامله به عرضه",
        category="commodity",
        subcategory="execution",
        market_type=MARKET_COMMODITY,
        formula="FillRate = Executed / Supply",
        formula_latex="FillRate = \\frac{Executed}{Supply}",
        interpretation="کیفیت جذب عرضه در بازار",
        threshold="نزدیک 1 بهتر",
        application="ارزیابی عمق تقاضا",
        caveat="نگاه صرف به ثبت سفارش اولیه",
        signal_direction="bullish_when_high",
    ),
]
