from domain.indicators.definitions import MARKET_FUTURES, MARKET_OPTION, SIGNAL_NEUTRAL, IndicatorMeta

OPTION_INDICATORS = [
    IndicatorMeta(
        name="intrinsic_value_call",
        display_name="ارزش ذاتی Call",
        category="option",
        subcategory="valuation",
        market_type=MARKET_OPTION,
        formula="Intrinsic_Call = max(S - K, 0)",
        formula_latex="Intrinsic_{Call} = \\max(S - K, 0)",
        interpretation="ارزش فوری اعمال اختیار خرید",
        threshold="---",
        application="تفکیک ارزش ذاتی و زمانی",
        caveat="نادیده‌گرفتن کارمزد و محدودیت اعمال",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="intrinsic_value_put",
        display_name="ارزش ذاتی Put",
        category="option",
        subcategory="valuation",
        market_type=MARKET_OPTION,
        formula="Intrinsic_Put = max(K - S, 0)",
        formula_latex="Intrinsic_{Put} = \\max(K - S, 0)",
        interpretation="ارزش فوری اعمال اختیار فروش",
        threshold="---",
        application="تفکیک ارزش ذاتی و زمانی",
        caveat="نادیده‌گرفتن کارمزد و محدودیت اعمال",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="time_value",
        display_name="ارزش زمانی (TV)",
        category="option",
        subcategory="valuation",
        market_type=MARKET_OPTION,
        formula="TV = OptionPrice - IntrinsicValue",
        formula_latex="TV = OptionPrice - IntrinsicValue",
        interpretation="بهای پرداخت شده برای زمان و عدم‌قطعیت",
        threshold="نزدیک سررسید کاهش می‌یابد",
        application="استراتژی فروش آپشن (Income)",
        caveat="خرید TV زیاد بدون دلیل",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="black_scholes_call",
        display_name="قیمت بلک-شولز Call",
        category="option",
        subcategory="pricing",
        market_type=MARKET_OPTION,
        formula="C = S0*N(d1) - K*e^(-rT)*N(d2)",
        formula_latex="C = S_0 N(d_1) - K e^{-rT} N(d_2)",
        interpretation="ارزش نظری اختیار خرید بر اساس مدل بلک-شولز",
        threshold="---",
        application="قیمت‌گذاری مرجع",
        caveat="فرض نرمال بودن و بازار کامل",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="black_scholes_put",
        display_name="قیمت بلک-شولز Put",
        category="option",
        subcategory="pricing",
        market_type=MARKET_OPTION,
        formula="P = K*e^(-rT)*N(-d2) - S0*N(-d1)",
        formula_latex="P = K e^{-rT} N(-d_2) - S_0 N(-d_1)",
        interpretation="ارزش نظری اختیار فروش بر اساس مدل بلک-شولز",
        threshold="---",
        application="قیمت‌گذاری مرجع",
        caveat="فرض نرمال بودن و بازار کامل",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="d1",
        display_name="d1 بلک-شولز",
        category="option",
        subcategory="pricing",
        market_type=MARKET_OPTION,
        formula="d1 = (ln(S0/K) + (r + σ^2/2)*T) / (σ*sqrt(T))",
        formula_latex="d_1 = \\frac{\\ln(S_0/K) + (r + \\sigma^2/2)T}{\\sigma\\sqrt{T}}",
        interpretation="متغیر کمکی اول مدل بلک-شولز",
        threshold="---",
        application="محاسبات قیمت‌گذاری",
        caveat="ورودی‌های ناسازگار",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="d2",
        display_name="d2 بلک-شولز",
        category="option",
        subcategory="pricing",
        market_type=MARKET_OPTION,
        formula="d2 = d1 - σ*sqrt(T)",
        formula_latex="d_2 = d_1 - \\sigma\\sqrt{T}",
        interpretation="متغیر کمکی دوم مدل بلک-شولز",
        threshold="---",
        application="محاسبات قیمت‌گذاری",
        caveat="ورودی‌های ناسازگار",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="implied_volatility",
        display_name="نوسان ضمنی (IV)",
        category="option",
        subcategory="volatility",
        market_type=MARKET_OPTION,
        formula="Price_mkt = BS(σ_impl)",
        formula_latex="Price_{mkt} = BS(\\sigma_{impl})",
        interpretation="نوسان قیمت‌گذاری‌شده توسط بازار",
        threshold="IV Rank بالا = گران‌تر",
        application="استراتژی معامله نوسان",
        caveat="قیاس IV خام بین سررسیدهای مختلف",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="mispricing",
        display_name="Mispricing",
        category="option",
        subcategory="arbitrage",
        market_type=MARKET_OPTION,
        formula="Mis = (Price_mkt - Price_model) / Price_model",
        formula_latex="Mis = \\frac{Price_{mkt} - Price_{model}}{Price_{model}}",
        interpretation="انحراف قیمت بازار از ارزش نظری",
        threshold="قدر مطلق بالا مهم",
        application="آربیتراژ نسبی",
        caveat="فرض درستی کامل مدل",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="delta",
        display_name="دلتا (Delta)",
        category="option",
        subcategory="greeks",
        market_type=MARKET_OPTION,
        formula="Δ_call = N(d1)",
        formula_latex="\\Delta_{call} = N(d_1)",
        interpretation="حساسیت قیمت آپشن به تغییر قیمت دارایی پایه",
        threshold="0 تا 1 برای Call، -1 تا 0 برای Put",
        application="هجینگ، انتخاب استرایک",
        caveat="نادیده‌گرفتن گاما",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="gamma",
        display_name="گاما (Gamma)",
        category="option",
        subcategory="greeks",
        market_type=MARKET_OPTION,
        formula="Γ = N'(d1) / (S0 * σ * sqrt(T))",
        formula_latex="\\Gamma = \\frac{N'(d_1)}{S_0 \\sigma \\sqrt{T}}",
        interpretation="نرخ تغییر دلتا نسبت به تغییر قیمت پایه",
        threshold="بالا = ریسک/فرصت بالا",
        application="معامله رویدادی",
        caveat="بی‌توجهی به گامای نزدیک سررسید",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="theta",
        display_name="تتا (Theta)",
        category="option",
        subcategory="greeks",
        market_type=MARKET_OPTION,
        formula="Θ = -∂Price/∂T",
        formula_latex="\\Theta = -\\frac{\\partial Price}{\\partial T}",
        interpretation="افت ارزش زمانی آپشن با گذشت زمان",
        threshold="منفی برای خریدار",
        application="استراتژی فروش آپشن",
        caveat="خرید آپشن بدون توجه به decay زمانی",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="vega",
        display_name="وگا (Vega)",
        category="option",
        subcategory="greeks",
        market_type=MARKET_OPTION,
        formula="Vega = S0 * sqrt(T) * N'(d1)",
        formula_latex="Vega = S_0 \\sqrt{T} N'(d_1)",
        interpretation="حساسیت قیمت آپشن به تغییر نوسان ضمنی",
        threshold="بالا = مهم در رویدادها",
        application="معامله نوسان",
        caveat="نادیده‌گرفتن skew",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="put_call_ratio",
        display_name="نسبت Put/Call",
        category="option",
        subcategory="sentiment",
        market_type=MARKET_OPTION,
        formula="PCR = Volume_put / Volume_call",
        formula_latex="PCR = \\frac{Vol_{put}}{Vol_{call}}",
        interpretation="تمایل نزولی نسبت به صعودی در بازار",
        threshold="> 1 ترس/بدبینی",
        application="سنجش احساسات بازار (Contrarian)",
        caveat="تفسیر بدون زمینه بازار",
        signal_direction="bearish_when_high",
    ),
    IndicatorMeta(
        name="iv_rank",
        display_name="رتبه نوسان ضمنی (IV Rank)",
        category="option",
        subcategory="volatility",
        market_type=MARKET_OPTION,
        formula="IV Rank = (IV - IV_min) / (IV_max - IV_min)",
        formula_latex="IV\\ Rank = \\frac{IV - IV_{min}}{IV_{max} - IV_{min}}",
        interpretation="جایگاه نوسان ضمنی فعلی در بازه تاریخی",
        threshold="> 0.8 بالا (گران)",
        application="تصمیم خرید/فروش آپشن",
        caveat="انتخاب پنجره زمانی نامناسب",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="gearing",
        display_name="اهرم عملیاتی (Gearing)",
        category="option",
        subcategory="risk",
        market_type=MARKET_OPTION,
        formula="Gearing = S * Δ / Premium",
        formula_latex="Gearing = \\frac{S \\times \\Delta}{Premium}",
        interpretation="حساسیت سود آپشن به تغییر قیمت سهم",
        threshold="> 5 ریسک و بازده بالا",
        application="انتخاب نماد برای نوسان‌گیری",
        caveat="تغییرات ناگهانی دلتا نزدیک سررسید",
        signal_direction=SIGNAL_NEUTRAL,
    ),
]

FUTURES_INDICATORS = [
    IndicatorMeta(
        name="fair_futures_price",
        display_name="قیمت منصفانه آتی",
        category="futures",
        subcategory="pricing",
        market_type=MARKET_FUTURES,
        formula="F0 = S0 * e^((r + c - y) * T)",
        formula_latex="F_0 = S_0 e^{(r + c - y)T}",
        interpretation="قیمت نظری آتی با هزینه نگهداری",
        threshold="---",
        application="آربیتراژ نقد-آتی",
        caveat="برآورد غلط هزینه‌ها و بازده",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="basis",
        display_name="مبنا (Basis)",
        category="futures",
        subcategory="pricing",
        market_type=MARKET_FUTURES,
        formula="Basis = S - F",
        formula_latex="Basis = S - F",
        interpretation="فاصله قیمت نقد و آتی",
        threshold="مثبت (Backwardation) / منفی (Contango)",
        application="تحلیل انتظارات تورمی",
        caveat="تفسیر بدون توجه به سررسید",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="basis_return",
        display_name="بازده Basis",
        category="futures",
        subcategory="pricing",
        market_type=MARKET_FUTURES,
        formula="BasisRet = (Basis_t - Basis_(t-1)) / F_(t-1)",
        formula_latex="BasisRet = \\frac{Basis_t - Basis_{t-1}}{F_{t-1}}",
        interpretation="تغییر انتظارات بازار در طول زمان",
        threshold="قدر مطلق بالا مهم",
        application="تحلیل تغییر انتظارات",
        caveat="نیاز به داده سری زمانی",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="contango_backwardation",
        display_name="Contango/Backwardation",
        category="futures",
        subcategory="structure",
        market_type=MARKET_FUTURES,
        formula="F > S (Contango), F < S (Backwardation)",
        formula_latex="F > S \\text{ (Contango)}, F < S \\text{ (Backwardation)}",
        interpretation="ساختار منحنی آتی نشان‌دهنده انتظارات",
        threshold="---",
        application="تحلیل موجودی و کمبود",
        caveat="نتیجه‌گیری بدون در نظر گرفتن هزینه حمل",
        signal_direction=SIGNAL_NEUTRAL,
    ),
]
