from domain.indicators.definitions import MARKET_INTERMARKET, SIGNAL_NEUTRAL, IndicatorMeta

INTERMARKET_INDICATORS = [
    IndicatorMeta(
        name="beta",
        display_name="بتا (β)",
        category="intermarket",
        subcategory="systematic_risk",
        market_type=MARKET_INTERMARKET,
        formula="β = Cov(R_s, R_m) / Var(R_m)",
        formula_latex="\\beta = \\frac{Cov(R_s, R_m)}{Var(R_m)}",
        interpretation="حساسیت بازده سهم به بازده کل بازار",
        threshold="> 1 تهاجمی، < 1 تدافعی",
        application="مدیریت ریسک سیستماتیک",
        caveat="ناپایداری بتا در رژیم‌های مختلف بازار",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="alpha",
        display_name="آلفا (Alpha)",
        category="intermarket",
        subcategory="performance",
        market_type=MARKET_INTERMARKET,
        formula="R_s - R_f = α + β(R_m - R_f) + ε",
        formula_latex="R_s - R_f = \\alpha + \\beta(R_m - R_f) + \\epsilon",
        interpretation="بازده مازاد نسبت به ریسک سیستماتیک",
        threshold="مثبت بهتر",
        application="ارزیابی عملکرد مدیران",
        caveat="کوتاه بودن نمونه آماری",
        signal_direction="bullish_when_positive",
    ),
    IndicatorMeta(
        name="correlation",
        display_name="همبستگی (ρ)",
        category="intermarket",
        subcategory="comovement",
        market_type=MARKET_INTERMARKET,
        formula="ρ = Cov(x,y) / (σ_x * σ_y)",
        formula_latex="\\rho = \\frac{Cov(x, y)}{\\sigma_x \\sigma_y}",
        interpretation="درجه هم‌حرکتی دو دارایی",
        threshold="نزدیک ±1 قوی",
        application="تنوع‌بخشی پورتفوی",
        caveat="فرض ثبات همبستگی",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="intermarket_rs",
        display_name="قدرت نسبی بین‌بازاری",
        category="intermarket",
        subcategory="relative_strength",
        market_type=MARKET_INTERMARKET,
        formula="RS = P_asset / P_benchmark",
        formula_latex="RS = \\frac{P_{asset}}{P_{benchmark}}",
        interpretation="لیدر یا لگارد بودن دارایی نسبت به معیار",
        threshold="روند صعودی = لیدر بازار",
        application="چرخش سرمایه بین بازارها",
        caveat="انتخاب benchmark ضعیف",
        signal_direction="bullish_when_rising",
    ),
]
