from domain.indicators.definitions import MARKET_MICROSTRUCTURE, SIGNAL_NEUTRAL, IndicatorMeta

MICROSTRUCTURE_INDICATORS = [
    IndicatorMeta(
        name="obi",
        display_name="عدم تعادل دفتر سفارش (OBI)",
        category="microstructure",
        subcategory="order_imbalance",
        market_type=MARKET_MICROSTRUCTURE,
        formula="OBI = (BidSize - AskSize) / (BidSize + AskSize)",
        formula_latex="OBI_t = \\frac{Q_t^{bid} - Q_t^{ask}}{Q_t^{bid} + Q_t^{ask}}",
        interpretation="غلبه تقاضا یا عرضه در لحظه",
        threshold="> 0.3 مثبت، < -0.3 منفی",
        application="تریگر کوتاه‌مدت برای ورود",
        caveat="اتکا به یک لحظه snapshot",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="obi_persistence",
        display_name="پایداری OBI",
        category="microstructure",
        subcategory="order_imbalance",
        market_type=MARKET_MICROSTRUCTURE,
        formula="OBI_Pers = (1/n) * sum(OBI_(t-i))",
        formula_latex="OBI\\_Pers = \\frac{1}{n} \\sum_{i=0}^{n-1} OBI_{t-i}",
        interpretation="ماندگاری عدم تعادل دفتر سفارش در طول زمان",
        threshold="بالا = معتبرتر",
        application="حذف نویز و تشخیص روند واقعی",
        caveat="نادیده‌گرفتن spoofing",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="ofi",
        display_name="OFI (Order Flow Imbalance)",
        category="microstructure",
        subcategory="order_imbalance",
        market_type=MARKET_MICROSTRUCTURE,
        formula="OFI = sum(BuyInitVol) - sum(SellInitVol)",
        formula_latex="OFI = \\sum BuyInitVol - \\sum SellInitVol",
        interpretation="عدم تعادل جریان سفارش‌های تهاجمی",
        threshold="مثبت = فشار خرید",
        application="تحلیل میکروساختار",
        caveat="نیازمند داده تیک",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="queue_consumption",
        display_name="نرخ مصرف صف فروش",
        category="microstructure",
        subcategory="queue_dynamics",
        market_type=MARKET_MICROSTRUCTURE,
        formula="QueueCons = -dQ_ask/dt",
        formula_latex="QueueCons = -\\frac{dQ_{ask}}{dt}",
        interpretation="سرعت خورده شدن صف فروش",
        threshold="بالا = جذب عرضه",
        application="تشخیص برگشت قیمتی",
        caveat="بدون بررسی همزمان قیمت",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="resilience",
        display_name="تاب‌آوری (Resilience)",
        category="microstructure",
        subcategory="liquidity",
        market_type=MARKET_MICROSTRUCTURE,
        formula="Res = (Depth_(t+Δ) - Depth_t) / Δ",
        formula_latex="Res = \\frac{Depth_{t+\\Delta} - Depth_t}{\\Delta}",
        interpretation="سرعت بازگشت عمق بازار پس از شوک",
        threshold="بالا = تاب‌آوری خوب",
        application="کیفیت نقدشوندگی",
        caveat="انتخاب بازه زمانی Δ نامناسب",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="downside_elasticity",
        display_name="کشسانی سمت نزول",
        category="microstructure",
        subcategory="impact",
        market_type=MARKET_MICROSTRUCTURE,
        formula="DownElas = ΔP⁻ / SellVol",
        formula_latex="DownElas = \\frac{\\Delta P^-}{SellVol}",
        interpretation="افت قیمت به ازای حجم فروش",
        threshold="پایین = جذب خوب",
        application="اندازه‌گیری impact فروش",
        caveat="نیاز به داده با فرکانس بالا",
        signal_direction="bullish_when_low",
    ),
    IndicatorMeta(
        name="vpin",
        display_name="VPIN",
        category="microstructure",
        subcategory="informed_trading",
        market_type=MARKET_MICROSTRUCTURE,
        formula="VPIN = (1/(n*V)) * sum(|V^B_i - V^S_i|)",
        formula_latex="VPIN = \\frac{1}{nV} \\sum_{i=1}^n |V_i^B - V_i^S|",
        interpretation="احتمال حضور معامله‌گر آگاه",
        threshold="بالا = ریسک informed trading",
        application="تشخیص معامله‌گران آگاه",
        caveat="نیازمند داده حجمی با دقت بالا",
        signal_direction="neutral",
    ),
    IndicatorMeta(
        name="aggression_ratio",
        display_name="نسبت تهاجم (AR)",
        category="microstructure",
        subcategory="aggression",
        market_type=MARKET_MICROSTRUCTURE,
        formula="AR = Vol_at_ask / Vol_total",
        formula_latex="AR = \\frac{Vol_{at\\_ask}}{Vol_{total}}",
        interpretation="میزان عجله خریداران برای معامله در قیمت فروش",
        threshold="> 0.6 تهاجم خریدار",
        application="تایید شروع رالی",
        caveat="نیاز به داده تیک",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="queue_fill_rate",
        display_name="نرخ پر شدن صف",
        category="microstructure",
        subcategory="queue_dynamics",
        market_type=MARKET_MICROSTRUCTURE,
        formula="dV_queue/dt",
        formula_latex="\\frac{dV_{queue}}{dt}",
        interpretation="سرعت مصرف یا ایجاد صف",
        threshold="مقدار منفی بزرگ = ریزش صف فروش",
        application="شناسایی بازگشت قیمتی (Reversal)",
        caveat="نیاز به داده لحظه‌ای",
        signal_direction=SIGNAL_NEUTRAL,
    ),
]
