from domain.indicators.definitions import MARKET_STATISTICAL, SIGNAL_NEUTRAL, IndicatorMeta

STATISTICAL_INDICATORS = [
    IndicatorMeta(
        name="linear_regression",
        display_name="رگرسیون خطی",
        category="statistical",
        subcategory="regression",
        market_type=MARKET_STATISTICAL,
        formula="Y = β0 + sum(βi * Xi) + ε",
        formula_latex="Y = \\beta_0 + \\sum \\beta_i X_i + \\epsilon",
        interpretation="اثر متغیرهای توضیحی بر بازده یا سود",
        threshold="p-value < 0.05",
        application="پیش‌بینی سری زمانی",
        caveat="هم‌خطی و overfit",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="logistic_regression",
        display_name="رگرسیون لجستیک",
        category="statistical",
        subcategory="classification",
        market_type=MARKET_STATISTICAL,
        formula="Pr(Y=1|X) = 1 / (1 + e^-(β0 + sum(βi*Xi)))",
        formula_latex="Pr(Y=1|X) = \\frac{1}{1 + e^{-(\\beta_0 + \\sum \\beta_i X_i)}}",
        interpretation="احتمال وقوع رخداد باینری",
        threshold="> 0.5 یا cutoff بهینه",
        application="احتمال شکست مقاومت",
        caveat="نیاز به داده متوازن",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="ttest",
        display_name="T-Test",
        category="statistical",
        subcategory="inference",
        market_type=MARKET_STATISTICAL,
        formula="t = (x̄ - μ0) / (s / sqrt(n))",
        formula_latex="t = \\frac{\\bar{x} - \\mu_0}{s / \\sqrt{n}}",
        interpretation="معنی‌داری آماری اختلاف میانگین",
        threshold="p < 0.05",
        application="تحلیل رویداد (Event Study)",
        caveat="چندآزمونی (Multiple Comparison)",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="composite_zscore",
        display_name="Z-Score ترکیبی",
        category="statistical",
        subcategory="scoring",
        market_type=MARKET_STATISTICAL,
        formula="Score = sum(w_j * Z_j)",
        formula_latex="Score = \\sum w_j Z_j",
        interpretation="امتیاز نهایی چندعاملی ترکیبی",
        threshold="رتبه‌بندی نسبی",
        application="اسکن بازار و رتبه‌بندی",
        caveat="وزن‌دهی بدون بک‌تست",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="hmm_regime",
        display_name="HMM / تشخیص رژیم",
        category="statistical",
        subcategory="regime_detection",
        market_type=MARKET_STATISTICAL,
        formula="P(S_t = j | X_t)",
        formula_latex="P(S_t = j | X_t)",
        interpretation="احتمال قرارگیری بازار در رژیم خاص",
        threshold="---",
        application="تشخیص فاز انباشت/توزیع",
        caveat="داده کم و تفسیر شتاب‌زده",
        signal_direction=SIGNAL_NEUTRAL,
    ),
]
