from domain.indicators.definitions import MARKET_STOCK, SIGNAL_NEUTRAL, IndicatorMeta

STOCK_INDICATORS = [
    IndicatorMeta(
        name="avg_real_buy",
        display_name="سرانه خرید حقیقی",
        category="stock",
        subcategory="ownership",
        market_type=MARKET_STOCK,
        formula="AvgRealBuy = Value_real_buy / N_real_buy",
        formula_latex="AvgRealBuy = \\frac{Val_{rb}}{N_{rb}}",
        interpretation="قدرت مالی متوسط هر خریدار حقیقی",
        threshold="وابسته به اندازه سهم",
        application="کشف خریدار درشت و بازیگران عمده",
        caveat="مقایسه بدون تعدیل اندازه شرکت",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="avg_real_sell",
        display_name="سرانه فروش حقیقی",
        category="stock",
        subcategory="ownership",
        market_type=MARKET_STOCK,
        formula="AvgRealSell = Value_real_sell / N_real_sell",
        formula_latex="AvgRealSell = \\frac{Val_{rs}}{N_{rs}}",
        interpretation="قدرت مالی متوسط هر فروشنده حقیقی",
        threshold="---",
        application="تحلیل فشار فروش",
        caveat="تفسیر منفرد بدون مقایسه با سرانه خرید",
        signal_direction="bearish_when_high",
    ),
    IndicatorMeta(
        name="bpr",
        display_name="قدرت خریدار (BPR)",
        category="stock",
        subcategory="ownership",
        market_type=MARKET_STOCK,
        formula="BPR = (Val_rb/N_rb) / (Val_rs/N_rs)",
        formula_latex="BPR = \\frac{Val_{rb}/N_{rb}}{Val_{rs}/N_{rs}}",
        interpretation="برتری میانگین خرید هر کد حقیقی بر فروش",
        threshold="> 1.5 خوب، > 2 قوی، > 3 طلایی",
        application="شناسایی پول هوشمند و قدرت خریداران",
        caveat="در نزدیکی مقاومت می‌تواند نشانه توزیع باشد",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="net_real_flow",
        display_name="خالص ورود پول حقیقی",
        category="stock",
        subcategory="ownership",
        market_type=MARKET_STOCK,
        formula="NetRealFlow = Value_real_buy - Value_real_sell",
        formula_latex="NetRealFlow = Val_{rb} - Val_{rs}",
        interpretation="جهت خالص حرکت نقدینگی حقیقی",
        threshold="مثبت خوب",
        application="تشخیص فاز انباشت و توزیع",
        caveat="مثبت بودن یک‌روزه کافی نیست، روند مهم است",
        signal_direction="bullish_when_positive",
    ),
    IndicatorMeta(
        name="nrf",
        display_name="خالص ورود پول نرمال‌شده (NRF)",
        category="stock",
        subcategory="ownership",
        market_type=MARKET_STOCK,
        formula="NRF = NetRealFlow / FreeFloatMcap",
        formula_latex="NRF = \\frac{NetRealFlow}{FreeFloatMcap}",
        interpretation="شدت ورود پول نسبت به اندازه سهم",
        threshold="هرچه بالاتر بهتر",
        application="مقایسه بین نمادهای مختلف",
        caveat="استفاده از مارکت‌کپ کل به جای شناوری مؤثر",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="ownership_change",
        display_name="تغییر مالکیت",
        category="stock",
        subcategory="ownership",
        market_type=MARKET_STOCK,
        formula="ΔOwn = Own_t - Own_(t-1)",
        formula_latex="\\Delta Own_t = Own_t - Own_{t-1}",
        interpretation="انتقال سهم بین بازیگران حقیقی و حقوقی",
        threshold="روند مهم‌تر از سطح",
        application="تحلیل ساختار مالکیت",
        caveat="تکیه بر یک روز تغییر",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="hhi_ownership",
        display_name="تمرکز مالکیت (HHI)",
        category="stock",
        subcategory="ownership",
        market_type=MARKET_STOCK,
        formula="HHI = sum(s_i^2)",
        formula_latex="HHI = \\sum s_i^2",
        interpretation="تمرکز سهامداری در دست چند بازیگر",
        threshold="بالاتر = تمرکز بیشتر",
        application="تشخیص float lock",
        caveat="نبود داده کامل سهامداری",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="absorption",
        display_name="ضریب جذب عرضه (ABS)",
        category="stock",
        subcategory="orderflow",
        market_type=MARKET_STOCK,
        formula="ABS = SellPressure / (|ΔPrice| + ε)",
        formula_latex="ABS_t = \\frac{SellPressure_t}{|R_t| + \\epsilon}",
        interpretation="فشار فروش زیاد با افت قیمت کم = جذب عرضه",
        threshold="بالا = جذب قوی",
        application="شناسایی کف‌های قیمتی",
        caveat="نیاز به بررسی همزمان حجم",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="supply_dryness",
        display_name="خشک شدن عرضه",
        category="stock",
        subcategory="orderflow",
        market_type=MARKET_STOCK,
        formula="Dryness = 1 - V / Avg(V, 20)",
        formula_latex="Dryness = 1 - \\frac{V_t}{\\bar{V}_{20}}",
        interpretation="کم شدن عرضه قابل فروش در بازار",
        threshold="بالا و همراه با حفظ قیمت",
        application="پیش‌درآمد شکست قیمتی",
        caveat="حجم کم ناشی از بی‌علاقگی را اشتباه نگیریم",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="corr_dry_ratio",
        display_name="نسبت حجم اصلاح به صعود",
        category="stock",
        subcategory="orderflow",
        market_type=MARKET_STOCK,
        formula="CorrDry = Mean Vol Down Days / Mean Vol Up Days",
        formula_latex="CorrDry = \\frac{\\text{Mean Vol Down Days}}{\\text{Mean Vol Up Days}}",
        interpretation="اصلاح کم‌عرضه یا پرعرضه",
        threshold="< 1 بهتر (اصلاح با حجم کمتر)",
        application="کیفیت پولبک",
        caveat="بدون تفکیک رژیم بازار",
        signal_direction="bullish_when_low",
    ),
    IndicatorMeta(
        name="dist_to_resistance",
        display_name="فاصله تا مقاومت",
        category="stock",
        subcategory="price_structure",
        market_type=MARKET_STOCK,
        formula="DistRes = (R* - C) / R*",
        formula_latex="DistRes = \\frac{R^* - C_t}{R^*}",
        interpretation="نزدیکی قیمت به ناحیه مقاومت",
        threshold="کوچک‌تر = نزدیک‌تر به شکست",
        application="زمان‌بندی ورود به معامله",
        caveat="بی‌توجهی به شکست‌های کاذب",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="resistance_touches",
        display_name="دفعات تست مقاومت",
        category="stock",
        subcategory="price_structure",
        market_type=MARKET_STOCK,
        formula="Touches = sum(1 if |(H_i - R*)/R*| < δ)",
        formula_latex="Touches = \\sum \\mathbf{1}\\left(\\left|\\frac{H_i - R^*}{R^*}\\right| < \\delta\\right)",
        interpretation="چند بار قیمت به مقاومت فشار آورده",
        threshold="زیاد + افت کم = مثبت",
        application="سنجش قدرت مقاومت",
        caveat="نیاز به تعریف δ مناسب",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="breakout_quality",
        display_name="کیفیت شکست (BOQ)",
        category="stock",
        subcategory="breakout",
        market_type=MARKET_STOCK,
        formula="BOQ = w1*Z(RVOL) + w2*Z(CLV) + w3*Z(RS) - w4*Z(DistRes)",
        formula_latex="BOQ = w_1 Z(RVOL) + w_2 Z(CLV) + w_3 Z(RS) - w_4 Z(DistRes)",
        interpretation="قدرت نسبی شکست مقاومت بر اساس ترکیب شاخص‌ها",
        threshold="هرچه بیشتر بهتر",
        application="رتبه‌بندی شکست‌ها",
        caveat="وزن‌دهی دل‌بخواهی بدون بک‌تست",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="breakout_acceptance",
        display_name="پذیرش بالای مقاومت",
        category="stock",
        subcategory="breakout",
        market_type=MARKET_STOCK,
        formula="Acceptance = count(C_(t+i) > R*) / m",
        formula_latex="Acceptance = \\frac{\\#\\{C_{t+i} > R^*\\}}{m}",
        interpretation="ماندگاری قیمت بالای سطح شکسته‌شده",
        threshold="> 0.6 خوب",
        application="فیلتر شکست کاذب",
        caveat="نگاه فقط به روز شکست",
        signal_direction="bullish_when_high",
    ),
]
