from domain.indicators.definitions import MARKET_COMMON, SIGNAL_NEUTRAL, IndicatorMeta

COMMON_INDICATORS = [
    IndicatorMeta(
        name="simple_return",
        display_name="بازده ساده",
        category="common",
        subcategory="return",
        market_type=MARKET_COMMON,
        formula="Rt = (Pt - Pt-1) / Pt-1",
        formula_latex="R_t = \\frac{P_t - P_{t-1}}{P_{t-1}}",
        interpretation="تغییر نسبی قیمت در یک دوره",
        threshold="بسته به بازار",
        application="سنجش عملکرد دوره‌ای",
        caveat="مقایسه مستقیم بین دارایی‌های با نوسان متفاوت",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="log_return",
        display_name="بازده لگاریتمی",
        category="common",
        subcategory="return",
        market_type=MARKET_COMMON,
        formula="rt = ln(Pt / Pt-1)",
        formula_latex="r_t = \\ln\\left(\\frac{P_t}{P_{t-1}}\\right)",
        interpretation="مناسب‌تر برای مدل‌سازی آماری و سری زمانی",
        threshold="---",
        application="سری زمانی، رگرسیون، مدل‌سازی مالی",
        caveat="استفاده در جایی که کاربر انتظار بازده درصدی ساده دارد",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="daily_range",
        display_name="دامنه روز",
        category="common",
        subcategory="volatility",
        market_type=MARKET_COMMON,
        formula="Range = H - L",
        formula_latex="Range_t = H_t - L_t",
        interpretation="شدت نوسان خام قیمت در طول روز",
        threshold="بالا = بی‌ثباتی بیشتر",
        application="تشخیص روزهای شوکی و نوسانات غیرعادی",
        caveat="بدون نرمال‌سازی نسبت به قیمت، مقایسه بین نمادها ممکن نیست",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="relative_range",
        display_name="دامنه نسبی",
        category="common",
        subcategory="volatility",
        market_type=MARKET_COMMON,
        formula="Range%% = (H - L) / C(t-1)",
        formula_latex="Range\\%_t = \\frac{H_t - L_t}{C_{t-1}}",
        interpretation="دامنه نرمال‌شده نسبت به قیمت بسته شدن قبلی",
        threshold="وابسته به دارایی",
        application="مقایسه نوسان بین نمادهای مختلف",
        caveat="مقایسه دارایی‌های با ساختار توقف/دامنه متفاوت",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="clv",
        display_name="موقعیت بسته شدن (CLV)",
        category="common",
        subcategory="price_structure",
        market_type=MARKET_COMMON,
        formula="CLV = (2C - H - L) / (H - L)",
        formula_latex="CLV_t = \\frac{2C_t - H_t - L_t}{H_t - L_t}",
        interpretation="محل بسته‌شدن قیمت در دامنه روز. نزدیک به 1 = بسته شدن در بالای دامنه",
        threshold="> 0.5 خوب، < -0.5 ضعیف",
        application="کیفیت کندل روز، پیش‌بینی گپ مثبت فردا",
        caveat="تفسیر بدون توجه به حجم می‌تواند گمراه‌کننده باشد",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="recovery_ratio",
        display_name="نسبت برگشت (Recovery)",
        category="common",
        subcategory="price_structure",
        market_type=MARKET_COMMON,
        formula="Recovery = (C - L) / (H - L)",
        formula_latex="Recovery_t = \\frac{C_t - L_t}{H_t - L_t}",
        interpretation="میزان برگشت قیمت از کف روز",
        threshold="بالاتر بهتر",
        application="تشخیص جذب فروش در طول روز",
        caveat="اشتباه گرفتن با سیگنال قطعی خرید",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="rvol",
        display_name="حجم نسبی (RVOL)",
        category="common",
        subcategory="volume",
        market_type=MARKET_COMMON,
        formula="RVOL = V / Average(V, 20)",
        formula_latex="RVOL_t = \\frac{V_t}{\\bar{V}_{n,t}}",
        interpretation="نسبت حجم امروز به میانگین حجم دوره",
        threshold="> 1.5 مهم، > 2 قوی",
        application="تایید شکست مقاومت، تشخیص حجم مشکوک",
        caveat="حجم زیاد همیشه به معنای پول هوشمند نیست",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="volume_zscore",
        display_name="Z-Score حجم",
        category="common",
        subcategory="volume",
        market_type=MARKET_COMMON,
        formula="Z(V) = (V - mu_V) / sigma_V",
        formula_latex="Z_t^V = \\frac{V_t - \\mu_V}{\\sigma_V}",
        interpretation="شدت غیرعادی بودن حجم معاملات بر اساس انحراف معیار",
        threshold="> 2 معنادار",
        application="غربال آماری روزهای پرحجم",
        caveat="فرض نرمال بودن کامل داده‌ها",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="trade_value",
        display_name="ارزش معاملات",
        category="common",
        subcategory="volume",
        market_type=MARKET_COMMON,
        formula="Value = P * V",
        formula_latex="Value_t = P_t \\times V_t",
        interpretation="اندازه پول جابه‌جا شده در بازار",
        threshold="هرچه بیشتر، معتبرتر",
        application="حذف خطای سهم‌های ارزان قیمت",
        caveat="اتکا به حجم بدون توجه به ارزش",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="float_turnover",
        display_name="گردش شناور",
        category="common",
        subcategory="volume",
        market_type=MARKET_COMMON,
        formula="Turnover = V / Float",
        formula_latex="Turnover_t = \\frac{V_t}{Float}",
        interpretation="نسبت حجم معامله به شناوری سهم",
        threshold="بالا = چرخش شدید سهامداری",
        application="کشف انباشت/توزیع",
        caveat="استفاده از شناوری اسمی به‌جای شناوری مؤثر",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="amihud_illiq",
        display_name="آمیهود (ILLIQ)",
        category="common",
        subcategory="liquidity",
        market_type=MARKET_COMMON,
        formula="ILLIQ = |Return| / Value",
        formula_latex="ILLIQ_t = \\frac{|R_t|}{Value_t}",
        interpretation="حساسیت قیمت به حجم معاملات (عدم نقدشوندگی)",
        threshold="کمتر = نقدشونده‌تر",
        application="شناسایی خشک شدن عرضه، عمق بازار",
        caveat="تحت تأثیر ارزش اسمی سهم",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="atr",
        display_name="میانگین دامنه واقعی (ATR)",
        category="common",
        subcategory="volatility",
        market_type=MARKET_COMMON,
        formula="TR = max(H-L, |H-C(t-1)|, |L-C(t-1)|), ATR = avg(TR, n)",
        formula_latex="TR_t = \\max(H-L, |H-C_{t-1}|, |L-C_{t-1}|), ATR_n = \\frac{1}{n}\\sum TR",
        interpretation="میانگین دامنه واقعی نوسان قیمت",
        threshold="بالاتر = نوسان بیشتر",
        application="تعیین حد ضرر، اندازه‌گیری نوسان",
        caveat="تحت تأثیر قیمت مطلق",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="normalized_volatility",
        display_name="نوسان نسبی",
        category="common",
        subcategory="volatility",
        market_type=MARKET_COMMON,
        formula="VolNorm = ATR / C",
        formula_latex="VolNorm_t = \\frac{ATR_t}{C_t}",
        interpretation="نوسان نرمال‌شده نسبت به قیمت",
        threshold="کمتر = آرام‌تر",
        application="مقایسه نوسان چند دارایی مختلف",
        caveat="نادیده‌گرفتن گپ‌ها و اخبار",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="compression",
        display_name="فشردگی (Compression)",
        category="common",
        subcategory="volatility",
        market_type=MARKET_COMMON,
        formula="Comp = ATR_short / ATR_long",
        formula_latex="Comp_t = \\frac{ATR_{short}}{ATR_{long}}",
        interpretation="کاهش انرژی نوسان نسبت به دوره بلندمدت",
        threshold="< 0.7 جالب توجه",
        application="پیش‌درآمد شکست قیمتی",
        caveat="فشردگی بدون توجه به جهت و قدرت نسبی",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="bb_width",
        display_name="پهنای باند بولینگر (BBW)",
        category="common",
        subcategory="volatility",
        market_type=MARKET_COMMON,
        formula="BBW = (Upper - Lower) / MA",
        formula_latex="BBW_t = \\frac{Upper - Lower}{MA}",
        interpretation="فشردگی یا انبساط باندهای بولینگر",
        threshold="در صدک‌های پایین مهم",
        application="اسکن سکون قبل از حرکت",
        caveat="استفاده منفرد بدون در نظر گرفتن حجم",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="relative_strength",
        display_name="قدرت نسبی (RS)",
        category="common",
        subcategory="comparative",
        market_type=MARKET_COMMON,
        formula="RS = P_asset / P_benchmark",
        formula_latex="RS_t = \\frac{P_t^a}{P_t^b}",
        interpretation="عملکرد دارایی نسبت به معیار (benchmark)",
        threshold="روند صعودی مطلوب",
        application="کشف لیدر بازار، شناسایی صنایع پیشرو",
        caveat="تمرکز فقط بر قیمت مطلق بدون توجه به ریسک",
        signal_direction="bullish_when_rising",
    ),
    IndicatorMeta(
        name="excess_return",
        display_name="بازده مازاد",
        category="common",
        subcategory="comparative",
        market_type=MARKET_COMMON,
        formula="ER = R_asset - R_benchmark",
        formula_latex="ER_t = R_t^a - R_t^b",
        interpretation="برتری بازده دارایی نسبت به benchmark",
        threshold="مثبت بهتر",
        application="مقایسه تاکتیکی عملکرد",
        caveat="انتخاب benchmark اشتباه",
        signal_direction="bullish_when_positive",
    ),
    IndicatorMeta(
        name="zscore_general",
        display_name="Z-Score عمومی",
        category="common",
        subcategory="statistical",
        market_type=MARKET_COMMON,
        formula="Z = (x - mu) / sigma",
        formula_latex="Z_{x,t} = \\frac{x_t - \\mu_x}{\\sigma_x}",
        interpretation="نرمال‌سازی مقادیر برای مقایسه بین ویژگی‌های مختلف",
        threshold="|Z| > 2 مهم",
        application="نرمال‌سازی داده‌ها، تشخیص نقاط پرت",
        caveat="فرض نرمال بودن توزیع",
        signal_direction=SIGNAL_NEUTRAL,
    ),
]
