from domain.indicators.definitions import MARKET_DEBT, SIGNAL_NEUTRAL, IndicatorMeta

DEBT_INDICATORS = [
    IndicatorMeta(
        name="bond_price",
        display_name="قیمت اوراق",
        category="debt",
        subcategory="pricing",
        market_type=MARKET_DEBT,
        formula="P = sum(CF_t / (1+y)^t)",
        formula_latex="P = \\sum_{t=1}^{T} \\frac{CF_t}{(1+y)^t}",
        interpretation="ارزش فعلی جریان‌های نقدی آتی",
        threshold="---",
        application="ارزش‌گذاری اوراق",
        caveat="استفاده از نرخ اسمی نامناسب",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="ytm",
        display_name="بازده تا سررسید (YTM)",
        category="debt",
        subcategory="return",
        market_type=MARKET_DEBT,
        formula="حل y از معادله قیمت: P = sum(CF_t / (1+y)^t)",
        formula_latex="P = \\sum_{t=1}^{T} \\frac{CF_t}{(1+y)^t} \\Rightarrow y = YTM",
        interpretation="نرخ سود مؤثر سالانه تا سررسید",
        threshold="مقایسه با نرخ بهره بانکی",
        application="ارزیابی جذابیت اوراق",
        caveat="فرض سرمایه‌گذاری مجدد کامل کوپن‌ها با همان نرخ",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="macaulay_duration",
        display_name="دوریشن مکالی (Macaulay Duration)",
        category="debt",
        subcategory="risk",
        market_type=MARKET_DEBT,
        formula="DM = sum(t * CF_t / (1+y)^t) / P",
        formula_latex="DM = \\frac{\\sum t \\times \\frac{CF_t}{(1+y)^t}}{P}",
        interpretation="میانگین وزنی زمان دریافت جریان‌های نقدی",
        threshold="بالاتر = حساسیت بیشتر به نرخ بهره",
        application="مدیریت ریسک نرخ بهره",
        caveat="استفاده بدون convexity",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="modified_duration",
        display_name="دوریشن تعدیل‌شده (Modified Duration)",
        category="debt",
        subcategory="risk",
        market_type=MARKET_DEBT,
        formula="Dmod = DM / (1 + y)",
        formula_latex="D_{mod} = \\frac{DM}{1 + y}",
        interpretation="کشش قیمت اوراق نسبت به تغییر نرخ بهره",
        threshold="بالاتر = ریسک بیشتر",
        application="تخمین تغییر قیمت",
        caveat="برای تغییرات بزرگ نرخ بهره ضعیف می‌شود",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="convexity",
        display_name="تحدب (Convexity)",
        category="debt",
        subcategory="risk",
        market_type=MARKET_DEBT,
        formula="Conv = (1/P) * sum(CF_t * t(t+1) / (1+y)^(t+2))",
        formula_latex="Conv = \\frac{1}{P} \\sum \\frac{CF_t \\cdot t(t+1)}{(1+y)^{t+2}}",
        interpretation="انحنای رابطه قیمت-نرخ بهره",
        threshold="مقدار مثبت (مزیت برای دارنده)",
        application="تحلیل دقیق‌تر تغییر قیمت",
        caveat="نادیده‌گرفتن در شوک‌های نرخ",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="credit_spread",
        display_name="اسپرد اعتباری (Credit Spread)",
        category="debt",
        subcategory="credit",
        market_type=MARKET_DEBT,
        formula="CS = YTM_corp - YTM_gov",
        formula_latex="CS = YTM_{corp} - YTM_{gov}",
        interpretation="پاداش ریسک نکول شرکت نسبت به اوراق دولتی",
        threshold="افزایش اسپرد = خطر ورشکستگی",
        application="تحلیل سلامت مالی ناشر",
        caveat="یکسان‌فرض‌کردن سررسیدها",
        signal_direction="bearish_when_high",
    ),
]
