from domain.indicators.definitions import MARKET_ENERGY, SIGNAL_NEUTRAL, IndicatorMeta

ENERGY_INDICATORS = [
    IndicatorMeta(
        name="crack_spread",
        display_name="اسپرد فرآورده (Crack Spread)",
        category="energy",
        subcategory="refining",
        market_type=MARKET_ENERGY,
        formula="CrackSpread = P_product - α * P_feed",
        formula_latex="CrackSpread = P_{product} - \\alpha P_{feed}",
        interpretation="حاشیه خام فرآوری نفت خام به فرآورده",
        threshold="بالاتر = سود بهتر",
        application="تحلیل پالایش و پتروشیمی",
        caveat="ساده‌سازی بیش‌ازحد ضریب α",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="refining_margin",
        display_name="حاشیه پالایشی (RM)",
        category="energy",
        subcategory="refining",
        market_type=MARKET_ENERGY,
        formula="RM = sum(wi*Pi) - sum(vj*Cj)",
        formula_latex="RM = \\sum_i w_i P_i - \\sum_j v_j C_j",
        interpretation="سود ناخالص ترکیب محصول و خوراک",
        threshold="صعودی بهتر",
        application="تحلیل صنعت پالایشی",
        caveat="بی‌توجهی به yield واقعی",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="sold_energy",
        display_name="انرژی فروخته‌شده",
        category="energy",
        subcategory="production",
        market_type=MARKET_ENERGY,
        formula="Energy = Cap * ut * Hours",
        formula_latex="Energy = Cap \\times ut \\times Hours",
        interpretation="خروجی واقعی نیروگاه",
        threshold="بالاتر بهتر",
        application="برآورد فروش نیروگاهی",
        caveat="فرض ظرفیت عملی کامل",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="electricity_revenue",
        display_name="درآمد برق",
        category="energy",
        subcategory="revenue",
        market_type=MARKET_ENERGY,
        formula="Revenue = Energy * Tariff",
        formula_latex="Revenue = Energy \\times Tariff",
        interpretation="اثر نرخ فروش برق بر درآمد",
        threshold="تابع تعرفه",
        application="ارزش‌گذاری نیروگاهی",
        caveat="بی‌توجهی به محدودیت شبکه",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="imbalance",
        display_name="ناترازی (Imbalance)",
        category="energy",
        subcategory="grid",
        market_type=MARKET_ENERGY,
        formula="Imbalance = Load - Generation",
        formula_latex="Imbalance = Load - Gen",
        interpretation="کمبود عرضه نسبت به تقاضا",
        threshold="مثبت زیاد = فشار نرخ",
        application="تحلیل سیکل برق",
        caveat="نادیده‌گرفتن دخالت سیاست‌گذار",
        signal_direction="bullish_when_high",
    ),
    IndicatorMeta(
        name="export_premium",
        display_name="پریمیوم صادراتی",
        category="energy",
        subcategory="trade",
        market_type=MARKET_ENERGY,
        formula="ExportPremium = (P_exp - P_dom) / P_dom",
        formula_latex="ExportPremium = \\frac{P_{exp} - P_{dom}}{P_{dom}}",
        interpretation="مزیت صادرات نسبت به فروش داخلی",
        threshold="مثبت بالا مهم",
        application="تحلیل رینگ صادراتی",
        caveat="چشم‌پوشی از محدودیت صادرات",
        signal_direction="bullish_when_high",
    ),
]
