from domain.indicators.definitions import MARKET_FUND, SIGNAL_NEUTRAL, IndicatorMeta

FUND_INDICATORS = [
    IndicatorMeta(
        name="nav",
        display_name="ارزش خالص دارایی (NAV)",
        category="fund",
        subcategory="valuation",
        market_type=MARKET_FUND,
        formula="NAV = (دارایی - بدهی) / تعداد واحد",
        formula_latex="NAV = \\frac{Assets - Liabilities}{Units}",
        interpretation="ارزش خالص هر واحد صندوق",
        threshold="---",
        application="ارزش‌گذاری واحدهای صندوق",
        caveat="تاخیر در به‌روزرسانی NAV",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="premium_discount",
        display_name="حباب/تخفیف (P/NAV)",
        category="fund",
        subcategory="valuation",
        market_type=MARKET_FUND,
        formula="PremDisc = (Price - NAV) / NAV",
        formula_latex="PremDisc = \\frac{Price - NAV}{NAV}",
        interpretation="فاصله قیمت معامله از ارزش واقعی",
        threshold="منفی = تخفیف (ارزندگی برای خرید)",
        application="آربیتراژ آماری",
        caveat="خرید صرفاً به‌خاطر تخفیف",
        signal_direction="bullish_when_negative",
    ),
    IndicatorMeta(
        name="tracking_error",
        display_name="خطای رهگیری (TE)",
        category="fund",
        subcategory="performance",
        market_type=MARKET_FUND,
        formula="TE = sqrt((1/(n-1)) * sum(R_fund - R_benchmark)^2)",
        formula_latex="TE = \\sqrt{\\frac{1}{n-1} \\sum (R_f - R_b)^2}",
        interpretation="انحراف بازده صندوق از شاخص مرجع",
        threshold="پایین بهتر",
        application="ارزیابی کیفیت مدیریت صندوق (ETF)",
        caveat="انتخاب benchmark نامناسب",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="sharpe_ratio",
        display_name="نسبت شارپ (Sharpe)",
        category="fund",
        subcategory="performance",
        market_type=MARKET_FUND,
        formula="Sharpe = (R_p - R_f) / σ_p",
        formula_latex="Sharpe = \\frac{R_p - R_f}{\\sigma_p}",
        interpretation="بازده به ازای هر واحد ریسک کل",
        threshold="> 1 خوب",
        application="مقایسه بازدهی ریسک‌تطبیق‌یافته",
        caveat="فرض نرمال بودن بازده‌ها",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="information_ratio",
        display_name="نسبت اطلاعات (IR)",
        category="fund",
        subcategory="performance",
        market_type=MARKET_FUND,
        formula="IR = (R̄_f - R̄_b) / TE",
        formula_latex="IR = \\frac{\\bar{R}_f - \\bar{R}_b}{TE}",
        interpretation="بازده فعال به ازای هر واحد خطای رهگیری",
        threshold="بالاتر بهتر",
        application="کیفیت مدیریت فعال",
        caveat="TE پایین با alpha پایین",
        signal_direction=SIGNAL_NEUTRAL,
    ),
]
