from domain.indicators.definitions import MARKET_SCORING, SIGNAL_NEUTRAL, IndicatorMeta

SCORING_MODELS = [
    IndicatorMeta(
        name="score_stock",
        display_name="امتیاز ترکیبی سهام",
        category="scoring",
        subcategory="stock",
        market_type=MARKET_SCORING,
        formula="Score = w1*Z(RVOL) + w2*Z(BPR) + w3*Z(NetRealFlow) + w4*Z(CLV) + w5*Z(RS) + w6*Z(ABS) - w7*Z(ILLIQ)",
        formula_latex="Score_{stock} = w_1 Z(RVOL) + w_2 Z(BPR) + w_3 Z(NetRealFlow) + w_4 Z(CLV) + w_5 Z(RS) + w_6 Z(ABS) - w_7 Z(ILLIQ)",
        interpretation="امتیاز ترکیبی چندعاملی برای سهام بر اساس نقدشوندگی، قدرت خریدار، جریان پول، ساختار قیمت و قدرت نسبی",
        threshold="رتبه‌بندی نسبی بین نمادها",
        application="اسکن و رتبه‌بندی سهام",
        caveat="وزن‌دهی نیاز به بهینه‌سازی و بک‌تست دارد",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="score_commodity",
        display_name="امتیاز ترکیبی کالا",
        category="scoring",
        subcategory="commodity",
        market_type=MARKET_SCORING,
        formula="Score = w1*Z(DSR) + w2*Z(CP) + w3*Z(PD) + w4*Z(Spread_dom/glob)",
        formula_latex="Score_{commodity} = w_1 Z(DSR) + w_2 Z(CP) + w_3 Z(PD) + w_4 Z(Spread_{dom/glob})",
        interpretation="امتیاز ترکیبی برای کالا بر اساس نسبت تقاضا به عرضه، درصد رقابت و اسپرد داخلی-جهانی",
        threshold="رتبه‌بندی نسبی",
        application="ارزیابی جذابیت عرضه‌های کالا",
        caveat="تأثیر نرخ ارز بر اسپرد",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="score_option",
        display_name="امتیاز ترکیبی آپشن",
        category="scoring",
        subcategory="option",
        market_type=MARKET_SCORING,
        formula="Score = w1*Z(-|Mispricing|) + w2*Z(IV Rank) + w3*Z(OI Change) + w4*Z(Vega) - w5*Z(ThetaRisk)",
        formula_latex="Score_{option} = w_1 Z(-|Mispricing|) + w_2 Z(IV Rank) + w_3 Z(OI Change) + w_4 Z(Vega) - w_5 Z(ThetaRisk)",
        interpretation="امتیاز ترکیبی برای اختیار معامله بر اساس mispricing، نوسان ضمنی و یونان",
        threshold="رتبه‌بندی نسبی",
        application="انتخاب آپشن برای معامله",
        caveat="مدل بلک-شولز می‌تواند خطای قیمت‌گذاری داشته باشد",
        signal_direction=SIGNAL_NEUTRAL,
    ),
    IndicatorMeta(
        name="score_bond",
        display_name="امتیاز ترکیبی اوراق",
        category="scoring",
        subcategory="debt",
        market_type=MARKET_SCORING,
        formula="Score = w1*Z(YTM) + w2*Z(-DurationRisk) + w3*Z(Convexity) + w4*Z(-CreditSpreadShock)",
        formula_latex="Score_{bond} = w_1 Z(YTM) + w_2 Z(-DurationRisk) + w_3 Z(Convexity) + w_4 Z(-CreditSpreadShock)",
        interpretation="امتیاز ترکیبی برای اوراق بدهی بر اساس بازده، ریسک نرخ بهره و تحدب",
        threshold="رتبه‌بندی نسبی",
        application="انتخاب اوراق برای سرمایه‌گذاری",
        caveat="ریسک نقدشوندگی در نظر گرفته نشده",
        signal_direction=SIGNAL_NEUTRAL,
    ),
]
